### ISSUE TITLE
$self->{ '_level' } is not set to 0 before new beautify requests

### ISSUE THREAD

**Issue by NisSAM** [darold/pgFormatter#100]
$self->{ '_level' } is not [re]set to 0 before new beautify requests
As a result next query will inherit it from the last value of the previous one. If after beautify it is not 0 on the next run we will have extra indentation 
```
  my $b = pgFormatter::Beautify->new();
  $b->{'_level'} = 5; # as it can be left after previous run
  $b->query( 'select * from dual' );
  $b->beautify();
  print $b->content(), "\n";
```
result is 
```
                    select
                        *
                    from
                        dual
```

**Comment by darold** [comment]
Commit 2bfac8c fix this issue.
