### ISSUE TITLE
DECLARE cursor issue

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#103]
If I format this with default parameters using version 3.4:

    DECLARE c_mvcc_demo CURSOR FOR
            SELECT xmin, xmax, cmax, *
            FROM mvcc_demo;
    SELECT 1;

I get this:

    DECLARE
        c_mvcc_demo CURSOR FOR
            SELECT
                xmin,
                xmax,
                cmax,
                *
            FROM
                mvcc_demo;
        SELECT
            1;

Notice the second SELECT is indented when it shouldn't be.

**Comment by darold** [comment]
Commit 01cc703 fixes this issue.

**Comment by bmomjian** [comment]
I can confirm this is fixed in git.
