### ISSUE TITLE
ORDER BY wrapping

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#104]
This query:

    SELECT * FROM pg_class ORDER BY relname;

when run through pg_format --wrap-after 80 using version 3.4 returns:

    SELECT *
    FROM pg_class
    ORDER BY
        relname;

I think the relname reference should be on the line above.

**Comment by darold** [comment]
Wrapping after number of column was not applied to ORDER BY and GROUP BY clauses, commit 49d0d0a fixes this.

**Comment by bmomjian** [comment]
I can confirm this is fixed in git.
