### ISSUE TITLE
USING clause crash

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#105]
In running this query through 3.4 with default parameters:

    WITH source AS source2 AS (
            DELETE FROM items USING source2
    )
    INSERT INTO old_orders SELECT order_id FROM source2;

causes this crash:

Uncaught exception: Use of uninitialized value in addition (+) at /usr/local/share/perl/5.24.1/pgFormatter/Beautify.pm line 547.
 at /usr/local/bin/pg_format line 19.
        main::__ANON__("Use of uninitialized value in addition (+) at /usr/local/shar"...) called at /usr/local/share/perl/5.24.1/pgFormatter/Beautify.pm line 547
        pgFormatter::Beautify::beautify(pgFormatter::Beautify=HASH(0x55eb54390110)) called at /usr/local/share/perl/5.24.1/pgFormatter/CLI.pm line 108
        pgFormatter::CLI::beautify(pgFormatter::CLI=HASH(0x55eb54383340)) called at /usr/local/share/perl/5.24.1/pgFormatter/CLI.pm line 67
        pgFormatter::CLI::run(pgFormatter::CLI=HASH(0x55eb54383340)) called at /usr/local/bin/pg_format line 49

If I remove the USING clause, it works.

**Comment by darold** [comment]
Last commit 2802e51 solve this issue.

**Comment by bmomjian** [comment]
I can confirm the fix is in git.
