### ISSUE TITLE
OVER and WINDOW clause indenting

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#106]
Using OVER and WINDOW in this query using version 3.4:

    SELECT RANK() OVER s AS dept_rank
    FROM emp
    WINDOW s AS (PARTITION BY department ORDER BY salary DESC)
    ORDER BY department, salary DESC;

generates this:

    SELECT
        RANK() OVER s AS dept_rank
        FROM
            emp WINDOW s AS (PARTITION BY department ORDER BY salary DESC)
    ORDER BY
        department,
        salary DESC;

If I change OVER to OVERX, the FROM is not indented.  The FROM should not be indented, and the WINDOW clause should be on its own line.

**Comment by darold** [comment]
Commit 8683973 might solve this issue, at least the case describe above.

**Comment by bmomjian** [comment]
I just checked git head, and I see this output:

    SELECT
        RANK() OVER s AS dept_rank
    FROM emp WINDOW s AS (PARTITION BY department ORDER BY salary DESC)
    ORDER BY
        department,
        salary DESC;

The WINDOW clause should be on its own line since it is a top-level clause, and not part of FROM.

**Comment by darold** [comment]
Ok, sorry I have understood the opposite by reading too fast your previous note. Commit 6c7d2af add this newline before the WINDOW keyword.

**Comment by bmomjian** [comment]
I can confirm this is fixed in git.  :+1:

**Comment by bmomjian** [comment]
I am seeing a new failure.  Using git (6c7d2af), this query:

    SELECT x, COUNT(x) OVER w, SUM(x) OVER w
    FROM generate_series(1, 10) AS f (x)
    WINDOW w AS ();

returns:

    SELECT
        x,
        COUNT(x) OVER w,
            SUM(x) OVER w
        FROM generate_series(1, 10) AS f (x)
        WINDOW w AS (
    );

Notice the SUM() is indented, and the window clause of () has a newline in it.

**Comment by darold** [comment]
Last two commits 5dc4526 and e22f3db4 fix both issues. Thanks a lot again Bruce for your help to improve this tool, there is lot of use cases that have not been tested and need reports.

**Comment by bmomjian** [comment]
I can confirm this is fixed in git.  :-)
