### ISSUE TITLE
WITH clause

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#107]
Using git (5dc4526), I see odd newlines in WITH column names, e.g. pg_format --wrap-after 80 run on:

    WITH driver (name) AS (
        SELECT DISTINCT
            unnest(xpath('//driver/text()',
                    doc))::text
        FROM printer
    )
    SELECT name
    FROM driver
    WHERE name LIKE 'hp%'
    ORDER BY 1;

returns:

    WITH driver (
        name
    ) AS (
        SELECT DISTINCT
            unnest(xpath('//driver/text()',
                    doc))::text
        FROM printer
    )
    SELECT name
    FROM driver
    WHERE name LIKE 'hp%'
    ORDER BY 1;

I don't think WITH (name) should have newlines in it.

**Comment by darold** [comment]
Commit b8591e7 fixes this issue. I have also updated the online demo site with all latest commits.

**Comment by bmomjian** [comment]
Uh, I think something is off --- I see an extra space before the column name:

    WITH driver ( name) AS (
         SELECT DISTINCT
            unnest(xpath('//driver/text()',
                    doc))::text
        FROM printer
    )
    SELECT name
    FROM driver
    WHERE name LIKE 'hp%'
    ORDER BY 1;

**Comment by bmomjian** [comment]
Here is another case, same parameters:

    WITH source (x1, x2) AS (
        SELECT 1
    )
    SELECT *
    FROM source;

formats to:

    WITH source ( x1,
        x2) AS (
        SELECT 1
    )
    SELECT *
    FROM source;

The x1 and x2 should be on the same line because of the wrap setting, and of course, no space before x1, as reported earlier.

**Comment by darold** [comment]
I should have test this case, fixed now with commit e079629.

**Comment by bmomjian** [comment]
So, the output I get now is:

    WITH source ( x1, x2 ) AS (
        SELECT 1
        )
    SELECT *
    FROM source;

Are the spaces before/after the x1/x2 arguments intended?  Do you do spaces in other such cases?  I don't see that happening for INSERT column list:

    INSERT INTO tab (col1, col2)
            VALUES (1, 2)

**Comment by darold** [comment]
There is also an extra indentation of the close parenthesis, will check that.

**Comment by darold** [comment]
Commits 5a367ca and 22dd09d fix both issues. Online site updated.

**Comment by bmomjian** [comment]
I can confirm this is fixed in git.  :-)
