### ISSUE TITLE
UPDATE SET wrapping

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#108]
For this query, run on git (5dc4526), using pg_format --wrap-after 80:

    UPDATE mvcc_demo
    SET val = val + 1
    WHERE val > 0;

I get:

    UPDATE mvcc_demo
    SET
        val = val + 1
    WHERE val > 0;

Seems 'val' should be on the line after SET.

**Comment by darold** [comment]
Fixed in commit d08b38c.

**Comment by bmomjian** [comment]
I can confirm it is fixed in git.  :-)
