### ISSUE TITLE
WINDOW clause parameters

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#109]
In running git (5dc4526) with options --wrap-after 80 on this query:

    SELECT name, department, salary, RANK() OVER s AS dept_rank, RANK() OVER () AS global_rank
    FROM emp
    WINDOW s AS (PARTITION BY department ORDER BY salary DESC)
    ORDER BY department, salary DESC;

    SELECT name, department, salary, RANK() OVER () AS global_rank, RANK() OVER s AS dept_rank
    FROM emp
    WINDOW s AS (PARTITION BY department ORDER BY salary DESC)
    ORDER BY department, salary DESC;
 
I get:

    SELECT name, department, salary, RANK() OVER s AS dept_rank, RANK() OVER () AS global_rank
    FROM emp
    WINDOW s AS (
        PARTITION BY department
    ORDER BY salary DESC)
    ORDER BY department, salary DESC;

    SELECT name, department, salary, RANK() OVER () AS global_rank, RANK() OVER s AS dept_rank
    FROM emp
    WINDOW s AS (PARTITION BY department ORDER BY salary DESC)
    ORDER BY department, salary DESC;

Notice the odd wrapping in the WINDOW clause in the first query.  The only difference between the two queries is that window name 's' is last in the target list of the last query, but not the first one.

**Comment by darold** [comment]
Last two commits 939b2b0 and 42ac9b2 and especially the last one fixes this new issue with WINDOWS clause.

**Comment by bmomjian** [comment]
I can confirm the fix is in git.
