### ISSUE TITLE
DISTINCT

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#110]
This query, with git (b8591e7) and with `--wrap-after 80`:

    SELECT DISTINCT relkind
    FROM pg_class
    ORDER BY 1;

generates:

    SELECT DISTINCT
        relkind
    FROM pg_class
    ORDER BY 1;

It seems there should not be a newline after DISTINCT.

**Comment by darold** [comment]
Commit 5f20644 fixes this issue.

**Comment by bmomjian** [comment]
I can confirm this is fixed in git.
