### ISSUE TITLE
testing idea

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#111]
I have run pg_format over the sql files in the Postgres distribution in src/test/regress/sql, and have found some odd formating.  I have put the output in [http://momjian.us/expire/pg_format/](http://momjian.us/expire/pg_format/).  Can you check that?  Would it help if I pointed out the problems?  Probably the most obvious problems are cases where indenting is not reset for the next command.

Also, I have also found that running it on drop_if_exists.sql never finishes.  Can you check that too?  I have put that file in that directory but did _not_ run pg_format on it.

**Comment by darold** [comment]
Good idea, I will try to test it this weekend. Let me check that to fix everything I can fix and your review will be welcome for a second pass.

**Comment by bmomjian** [comment]
Great, thanks.

**Comment by bmomjian** [comment]
I have updated the web versions on current git (aca6001)).

**Comment by bmomjian** [comment]
I have updated the output for git (848384b).

**Comment by bmomjian** [comment]
With current git (9fb9104), I am seeing these errors when re-running src/test/regress/sql/*.sql:

    Uncaught exception: Unmatched ( in regex; marked by <-- HERE in m/^( <-- HERE int4,$/ at /usr/local/share/perl/5.24.1/pgFormatter/Beautify.pm line 2868.
     at /usr/local/bin/pg_format line 19.

and

    Uncaught exception: Unmatched ( in regex; marked by <-- HERE in m/"alter1.=( <-- HERE procedure"/ at /usr/local/share/perl/5.24.1/pgFormatter/Beautify.pm line 2885.
     at /usr/local/bin/pg_format line 19.


drop_if_exists.sql doesn't hang anymore.  I have updated the URL contents.

**Comment by bmomjian** [comment]
I have updated the output for current git (2ec8baa).

**Comment by bmomjian** [comment]
I have updated the output for current git (698852d).

**Comment by bmomjian** [comment]
I have updated the output for current git (4050c2d).

**Comment by darold** [comment]
Thanks, I have started to fixes some issues related to XML last night and found some bad formatting with comment between EXCEPTION and WHEN keywords and in nested CTE.

**Comment by bmomjian** [comment]
You have made huge improvements in the past few weeks and I think we can consider this item closed.  Thanks so much!

**Comment by bmomjian** [comment]
Are you still working on this?  Would you like me to update the content at the URL?

**Comment by darold** [comment]
Hi Bruce, I'm still working on it as I'm not very satisfied about the FROM VALUE (...)  and with nested CTE formatting. But you can remove the content at the URL I have a local directory up-to-date. All tests cases will be included in the regression test for next release. I'm closing the issue.

Thanks you.
