### ISSUE TITLE
WINDOW and ORDER BY

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#112]
This query output with git (5a367ca) has the ORDER BY in a WINDOW clause not indented:

    SELECT
        salary,
        RANK() OVER s
    FROM emp
    WINDOW s AS (
    ORDER BY salary DESC)
    ORDER BY
        salary DESC;

It seems the ORDER BY should be on the same line as the WINDOW clause, like other keywords, e.g.:

    WINDOW w AS (PARTITION BY x >= 3 ORDER BY x RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW);

It seems having the ORDER BY as the first keyword after the open parentheses is causing it, e.g.:

    WINDOW w AS (
    ORDER BY x RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW);

**Comment by darold** [comment]
That's was exactly the problem, it is now fixed in commit aca6001.

**Comment by bmomjian** [comment]
I am confirm this is fixed in git.
