### ISSUE TITLE
CREATE FUNCTION indenting

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#113]
This is odd behavior --- CREATE FUNCTION causes the second INSERT to indent, with git (aca6001):

    CREATE FUNCTION sql_is_distinct_from (anyelement, anyelement)
        RETURNS boolean
        LANGUAGE sql
        AS ''
    ;
    INSERT INTO dom_table
        VALUES ('1');
        INSERT INTO dom_table
        VALUES ('1');

**Comment by bmomjian** [comment]
If you comment out the AS clause, there is no incorrect indenting.

**Comment by darold** [comment]
Commit c5a77c0 might fix this issue.

**Comment by bmomjian** [comment]
I can confirm this is fixed in git.
