### ISSUE TITLE
Crash with CREATE OPERATOR

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#114]
With current git (9fb9104), I am seeing a crash with this query from src/tools/regress/sql/*.sql:

    create operator alter1.=(procedure = alter1.same, leftarg  = alter1.ctype, rightarg = alter1.ctype);

The crash is:

    Uncaught exception: Unmatched ( in regex; marked by <-- HERE in m/"alter1.=( <-- HERE procedure"/ at /usr/local/share/perl/5.24.1/pgFormatter/Beautify.pm line 2885.
     at /usr/local/bin/pg_format line 19.

I am also seeing this fail on a different line:

     CREATE OPERATOR !== (
            PROCEDURE = int8ne,
            LEFTARG = bigint,
            RIGHTARG = bigint,
            NEGATOR = ===,
            COMMUTATOR = !==
    );

    DROP OPERATOR !==(bigint, bigint);

fails on this:

    Uncaught exception: Unmatched ( in regex; marked by <-- HERE in m/^!==( <-- HERE bigint,$/ at /usr/local/share/perl/5.24.1/pgFormatter/Beautify.pm line 2868.
     at /usr/local/bin/pg_format line 19.

**Comment by darold** [comment]
Fixed with commit 2ec8baa.

**Comment by bmomjian** [comment]
I can confirm this is fixed in git.
