### ISSUE TITLE
Hang on CREATE FUNCTION/CREATE VIEW

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#116]
This hangs with current git (698852d):

    CREATE FUNCTION customcontsel(internal, oid, internal, integer)
    RETURNS float8 AS 'contsel' LANGUAGE internal STABLE STRICT;
    CREATE VIEW attmp_view (unique1) AS SELECT unique1 FROM tenk1;
    
    SELECT 1;

There must be a blank line between the CREATE FUNCTION and CREATE VIEW, or before the SELECT 1, for it to hang.

**Comment by bmomjian** [comment]
Here is a smaller example:

    CREATE FUNCTION d(o) LANGUAGE i;

    CREATE TABLE a (u) AS SELECT u;

The blank line between is required.  The problem might be the LANGUAGE keyword.  Changing 'i' to 'sql' prevents the hang.

**Comment by darold** [comment]
Commit 247335e fixes the infinite loop resulting from undetected code delimiter in functions. New examples looks to be fixed too.

**Comment by bmomjian** [comment]
I can confirm it is fixed in current git.

**Comment by darold** [comment]
The CREATE TABLE (...) AS statement was not well formatted:
```
CREATE TABLE a (
    u) AS
SELECT
    u;
```
commit 8bdfa85 fix it.
```
CREATE TABLE a (
    u
) AS
SELECT
    u;
```
