### ISSUE TITLE
Slowness as input increases

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#117]
I noticed that when I process 75k lines, if I process it as 25 small files, it takes 3 minutes total, but if I process the input as 75k lines in one run, it takes 17 minutes.  Is this intended?  Is there some look-ahead, look-behind involved that would prevent linear performance?

**Comment by darold** [comment]
There is probably some performances lost when looking for function code separators. I will have a look.

**Comment by darold** [comment]
Last two commits 3bde22d and 576f568 improve speed. It only takes around 30 secs to format a 75k lines single file and around 45s for 248 files with same total number of lines.

**Comment by bmomjian** [comment]
Wow, 75k lines now runs in 50 seconds!  Doing it as 204 separate files now takes 78 seconds.  Big win!
