### ISSUE TITLE
Can we split the code into separate modules?

### ISSUE THREAD

**Issue by depesz** [darold/pgFormatter#12]
The way it's written now makes it hard to reuse the code without actually doing copy/paste and then modifying.
I'd like to split it into 3 separate modules:

- beautifier itself
- cgi app
- command line app

I can do the split, and it wouldn't require installation anyway - we can make the apps work by "figuring out" whether libraries are installed, or in directories where the program is, so nothing would change for the end user, with the exception that instead of using single file, there would be (at least) 5 of them, but that shouldn't be a problem, I think.

If you're OK with it, I'll start working on splitting the code.

The background for this is very simple - I'd like to make something like explain.depesz.com, but for queries, and your program seems to be too nice to replicate the effort from scratch. But given how it is written, would make it rather complicated to use in larger project.

**Comment by darold** [comment]
Let's go ! It was kept in a single Perl script because my need was to test pgBadger SQL beautifier, but I see that it is commonly used by others. Thanks for your help to build a better tool.

**Comment by depesz** [comment]
Just quick status update - I'm working on it, have the beautifier module ready (I think), and CLI at ~ 80% done. It takes longer than expected due to other responsibilities, but I'm getting there.

First pull request will be with simply split code (working of course), and after acceptance, I will provide next pull requests with more documentation, and possibly tests.

**Comment by darold** [comment]
Nothing is urging on this part so take your time and please don't worry about the new commits I will reapply them on the new code if necessary, that's not a problem.

**Comment by depesz** [comment]
https://github.com/darold/pgFormatter/pull/13 contains, as far as I know, all changes up to now.

Code is split into separate libraries, but pg_format still has the same functionality as it had earlier - including ability to serve as both CGI and CLI program.

**Comment by darold** [comment]
Pull request applied. To make things easiest for you've been added as a collaborator of this git repository, you may be able to push your changes without having to make a pull request. If you prefer to make pull request let me know I will remove this grant.

Thanks again for this great work.

**Comment by depesz** [comment]
Thank you. Will provide updated docs for the modules, but that, again, has to wait a bit. Will happen, though.
