### ISSUE TITLE
Not beautifying function

### ISSUE THREAD

**Issue by trraghav** [darold/pgFormatter#121]
```
create or replace function totalStrength 
  
--Defining return type 
return integer 
as 
total integer:=0; 
  
begin                         
  
-- calculating the sum and storing it in total  
select sum(strength) into total from section; 
return total; 
  
-- closing function 
end totalStrength;

```
Above function code conversion looks different then below one..

```
CREATE OR REPLACE FUNCTION totalRecords ()
RETURNS integer AS $total$
declare
	total integer;
BEGIN
   SELECT count(*) into total FROM COMPANY;
   RETURN total;
END;
$total$ LANGUAGE plpgsql;
```

**Comment by darold** [comment]
Yes putting comments before each SQL keywords is the best way to prevent SQL formatters to do good job. I will look if some cases can easily be fixed but you might also want to move comment written every where, this will shared the work :-)

**Comment by darold** [comment]
Won't be fixed this code is not PostgreSQL or standard SQL compliant
