### ISSUE TITLE
New Line After comma Fails

### ISSUE THREAD

**Issue by GiorgiModebadze** [darold/pgFormatter#123]
While trying to reformat sql, sometimes it fails the new line after comma request,

example below: 

![Screenshot 2019-06-25 at 14 46 39](https://user-images.githubusercontent.com/44123427/60099694-78bbca80-9758-11e9-8617-767afb1bd84b.png)

is there any reason for this? Is it because we use CTE before it ?

**Comment by GiorgiModebadze** [comment]
Anyone ?

**Comment by darold** [comment]
Sorry for the response delay. Please add a sample to reproduce as you see time is missing. You can use my private email if you want privacy on the sample gilles AT darold DOT net.

**Comment by GiorgiModebadze** [comment]
hi,

First thank you for the answer. 

This is a bit anonymous code of ours but it still triggers the problem 
[Result.txt](https://github.com/darold/pgFormatter/files/3397416/Result.txt)

error is on the line 101.

**Comment by darold** [comment]
Last two commits fix this issues. Online site updated.

**Comment by GiorgiModebadze** [comment]
@darold Great. Thank you a lot
