### ISSUE TITLE
Types with multiple parameters (such as PostGis' GEOMETRY) should not be broken up

### ISSUE THREAD

**Issue by spacedentist** [darold/pgFormatter#124]
Hi there!

I noticed that when you have parametrized types (I don't know if this is the correct term, I mean types that have configuration parameters such as `VARCHAR(20)`) with multiple parameters, then pgFormatter add line breaks after each comma, which looks a bit off.

An example for such a type is `GEOMETRY` in PostGis.

This is what pgFormatter produces in such a case:
```
CREATE TABLE "node" (
    id bigint NOT NULL PRIMARY KEY,
    "location" geometry (POINT,
        4326) NOT NULL,
    visible boolean NOT NULL
);
```

It would be much neater if there wasn't a line break within the type. Also there is a space between `geometry` and the opening bracket `(`, which I guess shouldn't be there. This would be the desired output, imho:
```
CREATE TABLE "node" (
    id bigint NOT NULL PRIMARY KEY,
    "location" geometry(POINT, 4326) NOT NULL,
    visible boolean NOT NULL
);
```

Would be nice if pgFormatter could adopt this. Hope this is not a controversial idea ;)

**Comment by darold** [comment]
This is just a bug fixed by commit 0f8c90e. Thanks for the report.
