### ISSUE TITLE
Formatting breaks when column starts with word "call"

### ISSUE THREAD

**Issue by rr0001** [darold/pgFormatter#125]
Hello, I am currently using version 4.0 with default settings from within DBeaver and it works great. However I noticed when a column starts with the word "call" without quotes, it breaks the formatting. Same when doing CREATE TABLE [...].

Here are some examples:

`SELECT call_one, two, three FROM test;`
`SELECT one_call, two, three FROM test;`
`SELECT "call_one", two, three FROM test;`
`SELECT one, call_two, three FROM test;`
`SELECT one, two_call, three FROM test;`

**Comment by darold** [comment]
Good catch, commit d6e919b fixes this issue.
