### ISSUE TITLE
Is it possible to add this formatter as a file watcher to my IntelliJ IDE?

### ISSUE THREAD

**Issue by dmca-faire** [darold/pgFormatter#128]
If so, are there instruction somewhere on how to do so?

**Comment by darold** [comment]
Hi,

I don't know about IntelliJ IDE, maybe there is a dedicated mailing list for this project where you can ask how to set an external code formatter. I keep this issue open some more time in case someone have an answer. Also in your side if you find the solution please give a feedback here some other can be interested too.

**Comment by dmca-faire** [comment]
Thank you. I've reached out to IntelliJ to find out. In addition, are there instructions on how to add the code formatter to my repo to be run as part of an automated build?

**Comment by darold** [comment]
I guess that you just have to install pgFormatter either using `yum install pgformatter` or `apt-get install pgformatter` or from sources using `perl Makefile.PL && make && sudo make install`. pg_format will be on your path so you just have to call to the program in what you find out with IntelliJ IDE.

**Comment by dmca-faire** [comment]
I've got it almost configured and can share once it's working.

I have the issue that if I try to write out to the same file I get an empty file, e.g., `pg_format file.sql -o file.sql` overwrites file.sql  as empty.

Daniel McAuley
Data Science
Faire ( https://www.faire.com/ )

Sent via Superhuman ( https://sprh.mn/?vip=daniel@faire.com )

**Comment by darold** [comment]
Commit af63e9e fix this issue by only opening the output file at end of the parsing.

**Comment by dmca-faire** [comment]
Thank you for putting out the quick fix. I'm now getting the following error when trying to write back out to the same file:

`pg_format file.sql -o file.sql

Uncaught exception: Deadly warning: Filehandle STDIN reopened as STDOUT only for output at (eval 22) line 150.

at /usr/local/bin/pg_format line 27.

main::__ANON__('Filehandle STDIN reopened as STDOUT only for output at (eval ...') called at (eval 22) line 150

pgFormatter::CLI::__ANON__('GLOB(0x7f85a3815e58)', '>', 'file.sql') called at / Library/Perl/5.18/pgFormatter/CLI.pm ( http://library/Perl/5.18/pgFormatter/CLI.pm ) line 131

pgFormatter::CLI::save_output('pgFormatter::CLI=HASH(0x7f85a3815b28)') called at / Library/Perl/5.18/pgFormatter/CLI.pm ( http://library/Perl/5.18/pgFormatter/CLI.pm ) line 73

pgFormatter::CLI::run('pgFormatter::CLI=HASH(0x7f85a3815b28)') called at /usr/local/bin/pg_format line 49

at /usr/local/bin/pg_format line 19.

main::__ANON__('Deadly warning: Filehandle STDIN reopened as STDOUT only for ...') called at / System/Library/Perl/5.18/Carp.pm ( http://system/Library/Perl/5.18/Carp.pm ) line 101

Carp::confess('Deadly warning: Filehandle STDIN reopened as STDOUT only for ...') called at /usr/local/bin/pg_format line 27

main::__ANON__('Filehandle STDIN reopened as STDOUT only for output at (eval ...') called at (eval 22) line 150

pgFormatter::CLI::__ANON__('GLOB(0x7f85a3815e58)', '>', 'file.sql') called at / Library/Perl/5.18/pgFormatter/CLI.pm ( http://library/Perl/5.18/pgFormatter/CLI.pm ) line 131

pgFormatter::CLI::save_output('pgFormatter::CLI=HASH(0x7f85a3815b28)') called at / Library/Perl/5.18/pgFormatter/CLI.pm ( http://library/Perl/5.18/pgFormatter/CLI.pm ) line 73

pgFormatter::CLI::run('pgFormatter::CLI=HASH(0x7f85a3815b28)') called at /usr/local/bin/pg_format line 49`

Daniel McAuley
Data Science
Faire ( https://www.faire.com/ )

Sent via Superhuman ( https://sprh.mn/?vip=daniel@faire.com )

**Comment by darold** [comment]
Strange that I've not got this error when testing, now I was able to reproduce. However commit 750f8c8 fix it.

**Comment by dmca-faire** [comment]
Thank did the trick! Thank you. With the code working, following these instructions got it working in an IntelliJ-based IDE: https://www.jetbrains.com/help/idea/using-file-watchers.html
