### ISSUE TITLE
Option to use tabs or custom spaces

### ISSUE THREAD

**Issue by jen-Ya** [darold/pgFormatter#129]
It would be great to have an option to use tabs instead of spaces!

Maybe something like `--space="\t"` or `--tabs`

As a workaround I am using sed: `pg_format | sed "s/^    /	/g"`

Thanks for the great work.

**Comment by darold** [comment]
Hi,

The default choice is to use space for a better granularity in the indentation but like you I often prefer to use tabulation. Last commit 3f9b4b1 add this feature:
```
    -T | --tabs        : use tabs instead of space characters, when used
                             spaces is set to 1 whatever is the value set to -s.
```

**Comment by jen-Ya** [comment]
Hi darold, thanks a lot! There is a small bug when using `--tabs`:

```sql
select
	*
from
	pg_stat_activity
where
	state	=	'active'	-- tabs should be used only for indentation
;
```

**Comment by darold** [comment]
Right, commit 568672d might fix this problem.

**Comment by jen-Ya** [comment]
I tested it on ~8k lines of sql and it worked fine, thank you!
