### ISSUE TITLE
Not all comments are removed

### ISSUE THREAD

**Issue by bradymholt** [darold/pgFormatter#130]
http://sqlformat.darold.net/

```
/** comment1 */
-- comment2

select * from table;
```

### Result
```
-- comment2

SELECT
    *
FROM
    TABLE;
```

This was previously reported here: https://github.com/darold/pgFormatter/issues/80 but it looks like the bug is back.

**Comment by darold** [comment]
Commit 75e2827 fixes this issue, thanks for the report.
