### ISSUE TITLE
Handling backslash in quotes

### ISSUE THREAD

**Issue by jen-Ya** [darold/pgFormatter#133]
Some backslashes in quotes produce wrong results.

Steps to reproduce:

```bash
echo "SELECT 'foo\' FROM bar;" | pg_format
```

result:

```sql
SELECT
    foo
FROM
    bar;
```

expected result:

```sql
SELECT
    'foo\'
FROM
    bar;
```

weirdly enough `'\foo'` and `'f\oo'` are handled correctly

**Comment by darold** [comment]
Commit 22f6d63 fixes this issue.

**Comment by jen-Ya** [comment]
Thank you, I tested it and it works fine.
