### ISSUE TITLE
Don't break lines in REVOKE sentences

### ISSUE THREAD

**Issue by fpuga** [darold/pgFormatter#135]
Thanks for a wonderful tool.

I expect this format `REVOKE ALL ON FUNCTION myschema.myfunction FROM PUBLIC;` but pg_format from the command line breaks it in several lines

```
$ echo "REVOKE ALL ON FUNCTION myschema.myfunction FROM PUBLIC;" | pg_format
REVOKE ALL ON FUNCTION myschema.myfunction
FROM
    PUBLIC;

$ pg_format --version
pg_format version 4.0
```

It's a bit weird, because the online tool, does not break the lines.

**Comment by darold** [comment]
Hi,

This should have been fixed by one of the last commit as I can not reproduce the issue with latest development code:
```
$ echo "REVOKE ALL ON FUNCTION myschema.myfunction FROM PUBLIC;" | ./pg_format
REVOKE ALL ON FUNCTION myschema.myfunction FROM PUBLIC;
```
I'm closing the issue.
