### ISSUE TITLE
Support for checking if the file is style compliant

### ISSUE THREAD

**Issue by palmerj** [darold/pgFormatter#137]
Would it be possible to add an option to check if the input file is style compliant? This would be useful for adding to CI pipelines. 

e.g 

```
pg_format -c input.sql
```
This will return nonzero if there are problems with the code style, which should stop the build on most systems.

**Comment by darold** [comment]
pgFormatter doesn't have some compliant analysis. It just parse a file, tokenize it and format what it found following a set of keywords. It can be any text file, pgFormatter will not complain at all. Also there is no problem with the code style, it just format what it found, there can not be any code style error.

**Comment by palmerj** [comment]
I guess I could at least check if input and output differ and then raise a warning in the CI tool.

**Comment by darold** [comment]
You can try but pgFormatter might format file that are not SQL statements, for example:
 ```
$ echo "I guess I could at least check if input and output differ and then raise a warning in the CI tool." | pg_format
```
``` 
I guess I could at least CHECK IF input AND output differ AND THEN
    raise a warning IN the CI tool.
```

**Comment by musjj** [comment]
Would love to see this too, can it be re-opened? Most formatters comes with a `--check` flag that raises an error when there's a difference.

> You can try but pgFormatter might format file that are not SQL statements, for example:

I mean, it's the user's responsibility to make sure that the tool is run on the right files, not the tool's.
