### ISSUE TITLE
Keep single empty lines

### ISSUE THREAD

**Issue by palmerj** [darold/pgFormatter#138]
More generally that #136 but can you please keep empty lines that already exist in file. e.g 

```sql
cat <<'EOF' | pg_format
BEGIN;

SELECT 1;

SELECT 2;

COMMIT;
EOF
```

and 

```sql
cat <<'EOF' | pg_format
-- some comment

SELECT 1;

SELECT 2;

-- some comment

```

should remain the same.

Removing more than single adjacent lines is ok.

**Comment by darold** [comment]
pgFormatter remove any extra newline after a comment, as for issue #136 this is intended.

The objective of a code formatter is to apply a format, for some rules it is possible to add an option for an alternate formatting. I must say that for these two issues I'm not very convinced that proposing an alternative to the default format is a good thing but I'm not closed to that. As I'm pretty happy with the current formatting and that it represent a non negligible extra work based on my spare time I set it at very low priority. I keep the issue open and classify it as enhancement.

**Comment by darold** [comment]
The extra newline in transaction block can be choose by using the `-g` option, this was relatively easy to allow the main work was on adding a new option. Unfortunately keeping the original newline formatting can not be done, this is much more complicated as it need to allow change of the global behavior of pgFormatter. I'm closing this issue as it will not be done.
