### ISSUE TITLE
Keep COMMENT ON formatting unchanged when using dollar quoting

### ISSUE THREAD

**Issue by palmerj** [darold/pgFormatter#140]
e.g 

```sql
cat <<'EOF' | pg_format
COMMENT ON TABLE foo.bar IS
$comment$
This is a nicely formatted comment line that spans
over multiple lines that should remain untouched

$comment$;
EOF
```

should remain the same.

Also note that if special keywords are in the comment all sorts of funny things occur like upper/lower case and indent for following blocks of SQL.

**Comment by darold** [comment]
Commit 0dec727 fixes this issue.
