### ISSUE TITLE
Compound FOREIGN KEY wraps unlike other constraints

### ISSUE THREAD

**Issue by victorandree** [darold/pgFormatter#143]
If I write a table definition with a compound foreign key, the column names are wrapped differently to other column names (in e.g. a compound primary key or unique index).

Example input:

```sql
CREATE TABLE foobar (
  id integer NOT NULL,
  version integer NOT NULL,
  prev_id integer NOT NULL,
  prev_version integer NOT NULL,
  PRIMARY KEY (id, version),
  UNIQUE (prev_id, prev_version),
  FOREIGN KEY (prev_id, prev_version) REFERENCES foobar (id, version)
);
```

Actual output from pgFormatter 4.1 on http://sqlformat.darold.net/

```sql
CREATE TABLE foobar (
    id integer NOT NULL,
    version integer NOT NULL,
    prev_id integer NOT NULL,
    prev_version integer NOT NULL,
    PRIMARY KEY (id, version),
    UNIQUE (prev_id, prev_version),
    FOREIGN KEY (prev_id,
        prev_version) REFERENCES foobar (id,
        version)
);
```

I think both referencing and target columns are formatted strangely. I think it would make sense to format it like other constraints on a single line i.e. like the input.

**Comment by darold** [comment]
Commit 4de2782 solves this issue.
