### ISSUE TITLE
Another formatting error

### ISSUE THREAD

**Issue by nagylzs** [darold/pgFormatter#145]
```
DO $$
BEGIN
    INSERT INTO table01 (id, user_id, group_id)
SELECT
    nextval('foobar'),
    ug.user_id,
    14
FROM
    table01 ug
WHERE
    ug.group_id = 13
    AND NOT EXISTS (
        SELECT
            *
        FROM
            table01 ug2
        WHERE
            ug2 = ug.user_id
            AND ug2.group_id = 14);
END;
$$;



```
The "SELECT" and the "INSERT" should be on the same level. For some reason, SELECT is dedented out.

**Comment by nagylzs** [comment]
I think this is because pgFormatter does not know what a DO BLOCK is. I found that the same is true for PERFORM. (But I may be wrong.)

**Comment by darold** [comment]
Commit 3748ba0 fixes this issue. DO BLOCK are well detected by pgFormatter it is taken like CREATE FUNCTION statements. Here the problem was that in INSERT statement only VALUES was taken in account. The patch adds detection of SELECT in INSERT statements.
