### ISSUE TITLE
Inconsistent behaviour with In

### ISSUE THREAD

**Issue by GiorgiModebadze** [darold/pgFormatter#146]
First: this is an options I am using : -b -B -s 2 -u 3 -f 3

this is the result i get:  (logic might seem a bit off) 
```
Select
  date
  , Case When Type In ('a'
    , 'b'
    , 'c') Then
    'a'
  Else
    'b'
  End As Type
  , Sum(count)
From (
  Select
    Date_trunc('month' , created_at) As date
    , Split_part(event_type , '_' , 1) As Type
    , Split_part(event_type , '_' , 2) As insurer
    , Count(*) As count
  From
    tb1
  Where
    Split_part(event_type , '_' , 2)
    In ('a' , 'b')
  Group By
    Date_trunc('month' , created_at)
    , Split_part(event_type , '_' , 1)
    , Split_part(event_type , '_' , 2)
  Order By
    Date_trunc('month' , created_at)
    Desc) tb1
Where
  Type <> 'c'
Group By
  date
  , Case When Type In ('a'
    , 'b') Then
    'a'
  Else
    'c'
  End
Order By
  date Desc;
```
But in some cases IN does this : In ('a' , 'b') and in others  In ('a'
    , 'b'
    , 'c')

Is it intended or is it a mistake ?

**Comment by GiorgiModebadze** [comment]
Second one is that it leaves desc on new line while in some other cases it does not:

Select
  Date_trunc('day' , last_updated_on)
  , Count(*)
From
  exports.a
Group By
  Date_trunc('day' , last_updated_on)
Order By
  Date_trunc('day' , last_updated_on)
  Desc;

Vs

Select
  Date_trunc('day' , last_updated_on)
  , Count(*)
From
  exports.a
Group By
  Date_trunc('day' , last_updated_on)
Order By
  day Desc;

**Comment by darold** [comment]
Commit d07819f remove case where a new line is append before ASC or DESC.
