### ISSUE TITLE
Single line formatting inside RETURNS TABLE (...)

### ISSUE THREAD

**Issue by ziyaddin** [darold/pgFormatter#147]
When I write a function that returns table, the tool formats `RETURNS TABLE (...)` part in single line like this:
![image](https://user-images.githubusercontent.com/1016523/66703379-1c8aaf80-ed23-11e9-922f-62f175bcdc3a.png)

I would be great to list these elements in multiple lines like this:

![image](https://user-images.githubusercontent.com/1016523/66703401-55c31f80-ed23-11e9-9411-c8774ee84064.png)

**Comment by darold** [comment]
Commit 4633466 fixes indentation in RETURNS TABLEclause.

**Comment by ziyaddin** [comment]
Thank you!
