### ISSUE TITLE
Facing issue with psql variables used in .sql file

### ISSUE THREAD

**Issue by girip11** [darold/pgFormatter#151]
Consider the below postgresql snippet.

```SQL
-- original snippet
\set user `echo $PGRST_DB_USER`
\set passwd `echo $PGRST_DB_PWD`
CREATE ROLE :user WITH LOGIN noinherit PASSWORD :'passwd';
```

The token `:'password'` is formatter to **`:<space>'password'`**. Output pasted from [sqlformat.darold.net](http://sqlformat.darold.net/).

```SQL
-- formatted snippet
\set user `echo $PGRST_DB_USER`
\set passwd `echo $PGRST_DB_PWD`
CREATE ROLE :user WITH LOGIN noinherit PASSWORD : 'passwd';
```

When I executed this sql query in psql, I am getting the below error.

```bash
psql:/docker-entrypoint-initdb.d/init.sql:13: ERROR:  syntax error at or near ":"
LINE 1: ...ROLE postgrest_auth WITH LOGIN noinherit PASSWORD : 'passwd'...
```

Same spacing issue when used with double quotes as well.  I am trying to follow the sql interpolation as in the documentation [SQL interpolation](https://www.postgresql.org/docs/9.5/app-psql.html#APP-PSQL-INTERPOLATION)  

Could you fix this to not format psql variables

**Comment by darold** [comment]
Commit 8171fc9 fixes this issue.

**Comment by darold** [comment]
and commit 96a81fa for the double quote.

**Comment by girip11** [comment]
Thanks @darold. How can I consume this bug fix. Should I wait for a new release 4.2?

**Comment by darold** [comment]
If you want to use latest development code you can use the demo site http://sqlformat.darold.net/ , it is always kept up to date with upstream, or download the code and install it:

```
wget https://github.com/darold/pgFormatter/archive/master.zip
unzip master.zip
cd pgFormatter-master/
perl Makefile.PL INSTALLDIRS=vendor
make
sudo make install
```
this might override installation.

**Comment by girip11** [comment]
Thanks @darold . I followed the steps and with the fix I don't see the reported issue. I am closing this issue.
