### ISSUE TITLE
Cast after case when shifts spaces

### ISSUE THREAD

**Issue by GiorgiModebadze** [darold/pgFormatter#153]
When I try to format this type of query:
SELECT
    CASE WHEN 1 = 1 THEN 2 ELSE 3 end::text AS col1, col2,  col3
FROM tb1

which casts type after case when using :: , everything after case when get shifted to the right. 
```SQL
SELECT
    CASE WHEN 1 = 1 THEN
        2
    ELSE
        3 end::text AS col1,
        col2,
        col3
    FROM
        tb1
```

if we use parentheses this is the formatting:

```SQL
SELECT
  (
    CASE WHEN 1 = 1 THEN
      2
    ELSE
      3
    END)::text AS col1,
  col2,
  col3
FROM
  tb1
```

Which is correct as lines do not shift to the right, but there are a lot of use cases when peoplle dont use parentheses and just go right with :: after case when, so If it can be considered as bug, it would be nice if you could correct it

Thank you

**Comment by darold** [comment]
Fixed with last commits. Use latest development code or online demo is it has been updated.

Thanks for the report.

**Comment by GiorgiModebadze** [comment]
Thank you a lot. Works perfectly
