### ISSUE TITLE
transaction management

### ISSUE THREAD

**Issue by prichardson211** [darold/pgFormatter#154]
First off... Thanks for maintaining such an awesome PGSQL formatter!

It seems to me that transaction management could be better managed.  After a commit the next begin is indented.  Perhaps it should not be?  Or maybe since the "END; " does not come until the end of the script, a better solution would be to line "END" with "BEGIN"?  Not sure I know the best solution, but this is definitely confusing for me.

CREATE OR REPLACE PROCEDURE foo (
)
AS $BODY$
DECLARE
BEGIN
    INSERT INTO bar (COLUMN)
    VALUES (1);
COMMIT;
    BEGIN
        INSERT INTO bar (COLUMN)
        VALUES (2);
    COMMIT;
        BEGIN
            INSERT INTO bar (COLUMN)
            VALUES (3);
        COMMIT;
END;
END;
END;
$BODY$
LANGUAGE plpgsql

**Comment by darold** [comment]
Commit 3855425 fixes this issues, thanks for the report.
