### ISSUE TITLE
Corruption of multiline text literals

### ISSUE THREAD

**Issue by mjfs** [darold/pgFormatter#163]
Integrity of multiline text is compromised when SQL query is formatted. Quoted text is left-padded with whitespace within single quotes.

Example of input SQL query:

```sql
SELECT '
This is
a multiline
text in
five
lines
' AS multiline_text,
1 AS random_int
```

Example of formatted SQL query output from pgFormatter (via default parameters `pg_format.pl input.sql -o output.sql`):

```sql
SELECT
    '
    This is
    a multiline
    text in
    five
    lines
    ' AS multiline_text,
    1 AS random_int
```

Text literals (everything between single quotes) in the output should remain exactly the same as in the input. As a consequence of left-padding currently the values of inline text columns are not equal to the ones before formatting.

**Comment by darold** [comment]
Commit 43859fb fixes this issue.
