### ISSUE TITLE
 Formatting issue with Row Number, Keywords

### ISSUE THREAD

**Issue by GiorgiModebadze** [darold/pgFormatter#165]
Hello,

There are some formatting issues we noticed while using pgFormatter

1) Row Number:

Code:
```SQL
SELECT
    a
    , b
    , Row_number() OVER (PARTITION BY Coalesce(c.order_id , c.id)ORDER BY c.id ASC)
    , e
    , d
    FROM
        c
```
How it Formats:
```SQL
SELECT
    a
    , b
    , Row_number() OVER (PARTITION BY Coalesce(c.order_id , c.id)
        ORDER BY
            c.id ASC)
        , e
        , d
    FROM
        c
```

Problem: It indents somehow after row Number all other columns further and further

2) Some Keywords:
I am not sure if it is by design or bug but will still mention. Some keywords, Like CONNECT, USAGE, PRIVILEGES, SEQUENCES are left out during the formatting. These are keywords we are using mainly during granting access to users.

3) It Also leaves out some keywords we use with DDL statements:
Example:
```SQL
CREATE TABLE sh.z (
    id SERIAL NOT NULL
    , b SmALLINT NULL
    , v TEXT NULL
    , d TexT NULL
    , e TiMESTAMP NULL
    , f BOOLEAN NOT NULL
    , g BOoLEAN NOT NULL)
```

**Comment by darold** [comment]
Both formatting issues are fixed, thanks for the report.
