### ISSUE TITLE
Data Type Case

### ISSUE THREAD

**Issue by HuanRuan** [darold/pgFormatter#167]
Hi 

As always thanks for the great work you continue producing.

Reading the v4.2. release notes, I wonder what the new 'Datatypes' case is. Is it about things like `numeric`, `varchar` etc.?

I tried this SQL 
```sql
SELECT 1::numeriC, cast(2 as vArchar(10))
```
on http://sqlformat.darold.net/ with default options, i.e. 'Datatypes - Lower case' but it didn't change the case of `numeriC` or `vArchar`.

Thanks
Huan

**Comment by darold** [comment]
Last commits f521c9c and 83e6d92 might fix the remaining issues with data type formatting.

**Comment by prichardson211** [comment]
I am not sure if this is related, however, when I use -U 2 to capitalize my datatypes I get an error 

`Deadly warning: Unknown option: U`

Thanks for the great work

**Comment by darold** [comment]
Works fine:
```
echo "SELECT 1::numeriC, cast(2 as vArchar(10))" | perl pg_format -U 2 -
SELECT
    1::NUMERIC,
    CAST(2 AS VARCHAR(10))
```
maybe you have an other version of pg_format in your path (/usr/bin vs /usr/local/bin ?)

**Comment by prichardson211** [comment]
It worked!

Thanks!
