### ISSUE TITLE
Add a way to identify beginning and end of each query

### ISSUE THREAD

**Issue by gajus** [darold/pgFormatter#169]
If pgFormatter could add a comment at the beginning and end of each statement, then I could extend https://github.com/gajus/pg-formatter to solve this problem https://stackoverflow.com/q/60145850/368691.

**Comment by darold** [comment]
I guess that splitting on `;` is not enough because of procedural code with multiple statement?

**Comment by gajus** [comment]
Cannot distinguish a standalone statement from a statement contained in a function declaration.

**Comment by gajus** [comment]
There have been some attempts to implement it, e.g. https://github.com/wttw/pgsplit

**Comment by darold** [comment]
I guess I can try to add an option (`-N`) to enable statement numbering that could prepend `-- Statement num: N` before each statement.

**Comment by darold** [comment]
Commit a3ee681 adds this feature.
```
    Add new command line option to add statement numbering:
    
        -N | --numbering      : statement numbering as a comment before each query.
    
    and new checkbox to CGI to activate the option.
```
demo site is up to date if you just want to test the feature.
