### ISSUE TITLE
--comma-break not adding newline in INSERT statements

### ISSUE THREAD

**Issue by bradymholt** [darold/pgFormatter#171]
Per the documentation:
>  -B | --comma-break    : in insert statement, add a newline after each comma

But, when passing in `--comma-break`, I am not seeing it add a newline after each comma.  Here's how it looks on the online formatter:

![CleanShot 2020-02-13 at 08 57 43@2x](https://user-images.githubusercontent.com/759811/74447420-f4c96680-4e3e-11ea-9dc5-0b39f976ef19.png)

I expect output like this:

```
INSERT INTO (
  field_one, 
  field_two, 
  field_three)
VALUES (
  1,
  2,
  3
);
```

**Comment by polobo** [comment]
I suppose it could read "add a newline between row expressions in the values clause".  Namely:
```
INSERT INTO (field_one, field_two, field_3)
VALUES (1,2,3),
(4,5,6),
(7,8,9);
```
This could apply to more than just insert.

**Comment by bradymholt** [comment]
I think this is a regression in version 4.2.

Version 4.1 with `--comma-break`:
```
INSERT INTO (field_one,
  field_two,
  field_three)
  VALUES (1,
    2,
    3);
```

Version 4.2 with `--comma-break`:
```
INSERT INTO (field_one, field_two, field_three)
  VALUES (1, 2, 3);
```

**Comment by darold** [comment]
Last commits might fix this issue
