### ISSUE TITLE
string format placeholders get broken in  Dollar-quoted String Constants

### ISSUE THREAD

**Issue by webervin** [darold/pgFormatter#178]
consider following [example](http://sqlfiddle.com/#!17/9eecb/50232) 
```sql
SELECT format($$ A %I B %s C %L %% D $$, 'pg_user', 22, null);
           format
-----------------------------
  A pg_user B 22 C NULL % D
(1 row)
```

after conversion at http://sqlformat.darold.net/ (claims to use version 4.3) [it becomes](http://sqlfiddle.com/#!17/9eecb/50234): 

```sql
SELECT
    format($$ A % I B % s C % L % % D $$, 'pg_user', 22, NULL);

```

and causes: `ERROR: unrecognized format() type specifier " " Hint: For a single "%" use "%%".`

**Comment by darold** [comment]
Thanks for the report, commit c7d7fc0 fixes this issue. Online site updated.
