### ISSUE TITLE
Connection limit formatting

### ISSUE THREAD

**Issue by nathancahill** [darold/pgFormatter#182]
Found an interesting edge case when creating roles.

Input:
```sql
create role admin with connection limit 3;
```

Output:
```sql
CREATE ROLE admin WITH connection
LIMIT 3;
```

It seems that the keyword `CONNECTION LIMIT` is missing when applied to `CREATE ROLE`, so there's no capitalization. It also might be interpreting `LIMIT` separately so it's adding a newline after `connection`. [Docs](https://www.postgresql.org/docs/current/sql-createrole.html)

**Comment by darold** [comment]
Good catch, commit 16bf4ac fixes this issue, thanks for the report. Online demo site updated.
