### ISSUE TITLE
Invalid formatting for table names matching Postgres functions

### ISSUE THREAD

**Issue by 0xjac** [darold/pgFormatter#185]
The following SQL file:

```sql
CREATE SCHEMA test;

CREATE TABLE test.position (
  id INTEGER PRIMARY KEY,
    lat DOUBLE PRECISION NOT NULL,
      long DOUBLE PRECISION NOT NULL,
imo INTEGER NOT NULL
);


CREATE TABLE position (
    id INTEGER PRIMARY KEY,
      lat DOUBLE PRECISION NOT NULL,
        long DOUBLE PRECISION NOT NULL,
imo INTEGER NOT NULL
);
```
produces the following output:
```sql
CREATE SCHEMA test;

CREATE TABLE test.position( id integer PRIMARY KEY, lat double PRECISION NOT NULL, long double PRECISION NOT NULL, imo integer NOT NULL
);

CREATE TABLE position( id integer PRIMARY KEY, lat double PRECISION NOT NULL, long double PRECISION NOT NULL, imo integer NOT NULL
);
```

Expected output:
```sql
CREATE SCHEMA test;

CREATE TABLE test.position (
    id integer PRIMARY KEY,
    lat double PRECISION NOT NULL,
    long double PRECISION NOT NULL,
    imo integer NOT NULL
);

CREATE TABLE position (
    id integer PRIMARY KEY,
    lat double PRECISION NOT NULL,
    long double PRECISION NOT NULL,
    imo integer NOT NULL
);
```
This only happens if the table name matches a postgres function. I guess it is detected as a function despite the `TABLE` keyword.

Tested on version 4.3

Edit: Passing `--function-case 2` (= to uppercase) will make the table name uppercase as well, as in `CREATE TABLE test.POSITION( id integer PRIMARY KEY --...`

**Comment by 0xjac** [comment]
I've also noticed that the handling of type case for `DOUBLE PRECISION` is incorrect.

From the example above, the `PRECISION` is not converted to lower case. This happens even when playing with the `--type-case` argument.

Let me know if you want me to open a separate issue about it.

**Comment by darold** [comment]
Commit 07dbe65 fixes this issue, thanks for the report. Online demo site updated.
