### ISSUE TITLE
Incorrect case conversion for datatypes of more than one word and trailing new lines

### ISSUE THREAD

**Issue by 0xjac** [darold/pgFormatter#186]
Datatypes  with more than one word, such as `double precision` are not handled correctly when changing their case.

The following SQL input:

```sql
CREATE TABLE public.test (
    value double precision,
    ts1 timestamp (4) with time zone,
    ts2 timestamp with time zone,
    ts1 timestamp (4) without time zone,
    ts2 timestamp without time zone,
    t1 time (4) with time zone,
    t2 time with time zone,
    t1 time (4) without time zone,
    t2 time without time zone,
    d1 interval second (6),
    d2 interval second,
    d3 interval (6)
);
```
Produces the following output when calling `pg_formatt` with `--type-case 2` (Change case of the data type to uppercase):

```sql
CREATE TABLE public.test (
    value DOUBLE precision,
    ts1 TIMESTAMP(4
) with TIME ZONE,
    ts2 TIMESTAMP with TIME ZONE,
    ts1 TIMESTAMP(4) without TIME ZONE,
    ts2 TIMESTAMP without TIME ZONE,
    t1 TIME(4
) with TIME ZONE,
    t2 TIME with TIME ZONE,
    t1 TIME(4) without TIME ZONE,
    t2 TIME without TIME ZONE,
    d1 INTERVAL second (6),
    d2 INTERVAL second,
    d3 INTERVAL(6)
);


```

Expected output
```sql
CREATE TABLE public.test (
    value DOUBLE PRECISION,
    ts1 TIMESTAMP (4) WITH TIME ZONE,
    ts2 TIMESTAMP WITH TIME ZONE,
    ts1 TIMESTAMP (4) WITHOUT TIME ZONE,
    ts2 TIMESTAMP WITHOUT TIME ZONE,
    t1 TIME (4) WITH TIME ZONE,
    t2 TIME WITH TIME ZONE,
    t1 TIME(4) WITHOUT TIME ZONE,
    t2 TIME WITH TIME ZONE,
    d1 INTERVAL SECOND (6),
    d2 INTERVAL SECOND,
    d3 INTERVAL(6)
);
```

Notice the case of `precision` for `value`, the `with`/`without` for the timestamp and timestamps, and the `second` for the intervals.

Also note the `(p)` for the date/time types where the space before is removed and the extra line break in some cases.

I also notice there were 2 trailing new lines at the end of the file.

Tested with version 4.3 and [online](http://sqlformat.darold.net/) after the fix for #185 was deployed. (Thanks for fixing that so quickly by the way!)

**Comment by darold** [comment]
Commit c50f09b fixes this issues as well as several other problem with data type and function case conversion. There is still issue in formatting interval cast, I will work on it later.
