### ISSUE TITLE
How to pass query via stdin

### ISSUE THREAD

**Issue by vigneshrajarr** [darold/pgFormatter#187]
I tried,
1. `pg_format -` and entered the query in the following line.
2. `pg_format - 'select * from customers;'` (also with double quotes)
Nothing worked.
Passing sql files works. 
How to execute via stdin ?

**Comment by darold** [comment]
you must type `ctrl+d` after typing your query.

**Comment by darold** [comment]
and if you want to use a one liner command use the following:
```
echo "select * from customers;" | pg_format
```

**Comment by vigneshrajarr** [comment]
Both works
> you must type `ctrl+d` after typing your query.

Please add this to README.

**Comment by darold** [comment]
Done, commit 4f9e85c adds the following to documentation:
```
  Formatting from stdin
    You can execute pg_format without any argument or - to give the SQL code
    to format through stdin.

    If you use the interactive mode you have to type `ctrl+d` after typing
    your SQL statement to format to end the typing.

            $ pg_format
            select * from customers;
            < ctrl+d >

    You can use stdin in a one liner as follow:

            echo "select * from customers;" | pg_format
```
