### ISSUE TITLE
Delimiters

### ISSUE THREAD

**Issue by aubertc** [darold/pgFormatter#191]
Hi,

as far as I know, it is needed to use `DELIMITER` to define e.g. procedures (cf. for instance <https://stackoverflow.com/questions/10259504/delimiters-in-mysql>).

A simple example of (valid, as far as I can tell) code would be:

```.mysql
DELIMITER $$ -- We change the delimiter: it is now $$ instead of ;
CREATE PROCEDURE TEST()
BEGIN
    SELECT "Hello World";
END;
$$ -- This is the delimiter that marks the end of the procedure definition.
DELIMITER ; -- Now, we want ";" to be the "natural" delimiter again.

CALL TEST(); 
```

However, `pg_format test.sql -o format.sql` transform it into:

```.mysql
DELIMITER $$ -- We change the delimiter: it is now $$ instead of ;
CREATE PROCEDURE TEST ()
BEGIN
    SELECT
        "Hello World";

END;

$$ -- This is the delimiter that marks the end of the procedure definition.
DELIMITER;

-- Now, we want ";" to be the "natural" delimiter again.
CALL TEST ();
```
which cannot be executed, as `DELIMITER;` is not correct (there need to be a space between `DELIMITER` and `;`).

As stated [in the documentation of mysql](https://dev.mysql.com/doc/refman/8.0/en/stored-programs-defining.html):

 >  You can redefine the delimiter to a string other than //, and the delimiter can consist of a single character or multiple characters. You should avoid the use of the backslash (\) character because that is the escape character for MySQL. 

So, any character string without space following `DELIMITER` could be the new delimiter, but I believe that `//` and `$$` are fairly standard.

**Comment by darold** [comment]
pgFormatter is dedicated to PostgreSQL and claim to be more or less working with any SQL standard compliant database. In PostgreSQL the code delimiter is use to enclosed the code of the function (default to single quote `'`) which is different from the statement delimiter, example:
```
CREATE FUNCTION plus(first integer, second integer) RETURNS integer AS $$
BEGIN
RETURN first + second;
END; $$
LANGUAGE PLPGSQL;
```
it looks like mysql mixed the statement and code delimiter and if you want to create a function you must change the "object" delimiter.

Well, I can not promise a result but in respect to your submission I will try to handle this special case.

For my curiosity, can you tell me the percentage of the "well done" job of pgFormatter with mysql you have experienced? Outside the delimiter issue of course.

**Comment by aubertc** [comment]
> it looks like mysql mixed the statement and code delimiter and if you want to create a function you must change the "object" delimiter.

I believe this is a correct interpretation of how it is implemented. It's a 3 steps procedure, really: 1. Change the delimiter, 2. Define your function, using the "standard" delimiter, 3. Restore the delimiter.



> Well, I can not promise a result but in respect to your submission I will try to handle this special case.

Thanks a lot, I really appreciate it, and your responsiveness.



> For my curiosity, can you tell me the percentage of the "well done" job of pgFormatter with mysql you have experienced? Outside the delimiter issue of course.

I'm not using it on super complicated mysql code, but everything is perfect, except this small issue. Table and schema creation, insertion, update, deletion, select queries, triggers, … I could not see any issue.

The only thing I could find missing (but it's not related to mysql) is not being able to wrap long lines that are commented.
For instance, it would be neat if pgFormatter could transform

```.mysql
-- This is an extremely long comment, way more than the recommended 80 lines that is common in Unix-like systems.
```

into 


```.mysql
-- This is an extremely long comment, way more than the recommended 80 lines 
-- that is common in Unix-like systems.
```

and similarly for `/*…*/` comments.

If that's something you'd like to look into, I can open a separate issue, and try to document it better.

Thanks again!

**Comment by darold** [comment]
Commit 8c26e1a fixes this issue.

**Comment by darold** [comment]
With last commits comment starting with `--` are now rewritten by `--wrap-limit`. I will work on the form `/* ... */` later.

**Comment by aubertc** [comment]
Thank you so much, that's perfect!

**Comment by aubertc** [comment]
I'm sorry, I commented without testing: I believe your fix does not work. I'll investigate and report my findings.

The wrapping of the comments is perfect, though!

**Comment by aubertc** [comment]
The following code:

```.mysql
DROP SCHEMA IF EXISTS TEST_ISSUE_191;
CREATE SCHEMA TEST_ISSUE_191;
USE TEST_ISSUE_191;

CREATE TABLE TEST (
  A INT
);

INSERT INTO TEST VALUES (1);

DELIMITER //
CREATE PROCEDURE PROCEDURE_TEST ()
BEGIN
  SELECT *
  FROM TEST;
END;
//
DELIMITER ;

CALL PROCEDURE_TEST ();
```
is formatted to

``` .mysql
DROP SCHEMA IF EXISTS HW_ProcedureExamples;

CREATE SCHEMA HW_ProcedureExamples;

USE HW_ProcedureExamples;

CREATE TABLE TEST (
    A int
);

INSERT INTO TEST
    VALUES (1);

DELIMITER $$ CREATE PROCEDURE PROCEDURE_TEST ()
BEGIN
    SELECT
        *
    FROM
        TEST;

END;

$$ DELIMITER ;

CALL PROCEDURE_TEST ();
```

and similarly if `//` is used instead of `$$`.
The issue is that a new line should be introduced after `$$`, on two lines:

- `DELIMITER $$ CREATE PROCEDURE PROCEDURE_TEST ()`
- `$$ DELIMITER ;`

I checked the code, and I was under the impression that 
https://github.com/darold/pgFormatter/blob/master/lib/pgFormatter/Beautify.pm#L2661
was taking care of that, but I probably misunderstood your code.

**Comment by aubertc** [comment]
(I guess the comments in my code was hiding this in my previous example…)

**Comment by darold** [comment]
Ok, it was a bit more complicated than what I've though, commit c4a006c might fix the issue.

**Comment by aubertc** [comment]
Excellent, it even works with `//` _and_ `$$`.
Thanks a lot for the quick and efficient fix!
