### ISSUE TITLE
Incorrect case transformation on conflicting table/column names

### ISSUE THREAD

**Issue by 0xjac** [darold/pgFormatter#197]
When a table or a column has a name which matches the name of a function or a type, and pg_format is asked to convert the case of functions and types, those table column and table names are converted as well.

For example, considering the table below:

```sql
create table position (
	latitude double precision,
	longitude double precision,
	name text
);
```
and called with pgFormatter as follow: `./pg_format -f 2 -u 2 -U 2 -L <file.sql>` produces the following output:

```sql
CREATE TABLE POSITION (
    latitude DOUBLE precision,
    longitude DOUBLE precision,
    NAME TEXT
);
```

I would expect to have the following result:

```sql
CREATE TABLE position (
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    name TEXT
);
```

I see 3 problem with the current output:

1. The `position` table name should not be transformed to upper case
1. The `name` column name should not be transformed to upper case
1. The `double precision` type should be fully converted to upper case (might be a regression from #186)

> Tested locally with latest commit on master: 91983eb

**Comment by darold** [comment]
Commits 50850a51 and e13d03d fix this issue.
