### ISSUE TITLE
Inconsistent function call formatting

### ISSUE THREAD

**Issue by svenklemm** [darold/pgFormatter#203]
Function calls that are not native postgres functions will get formatted differently with a space between the function name and the opening parens of the argument list. It would be nice if there was an option to treat unknown functions like native postgres functions or have an option to supply additional known functions.

**Comment by darold** [comment]
Commit 8c98f61 adds new command line option `--extra-function` and associated configuration directive `extra-function`.  pgFormatter applies some formatting to the PostgreSQL internal functions call but it can not detect user defined function. It is possible to defined a list of functions into a file (one function name per line) and give it to pgFormatter through the `--extra-function` option that will be formatted as PostgreSQL internal functions.

For example:
```
echo "MyFunction" > /tmp/fct.list
perl pg_format --extra-function /tmp/fct.list t/test-files/ex61.sql
```
