### ISSUE TITLE
Formatting breaks pgtrgm operator

### ISSUE THREAD

**Issue by hixus** [darold/pgFormatter#204]
Formatting seems to add space between [pgtrgm word boundary operator](https://www.postgresql.org/docs/9.6/pgtrgm.html) which brakes it

Working sample

`SELECT
	*
FROM
	"addresses"
ORDER BY
	'Something' <<-> address
LIMIT 10;`

but after formatting space is added between << and -> 

`SELECT
	*
FROM
	"addresses"
ORDER BY
	'Something' << -> address
LIMIT 10;`

which results `Query 1 ERROR: ERROR:  operator does not exist: -> text`

**Comment by darold** [comment]
Commit f89e535 fixes this issue. Thanks.
