### ISSUE TITLE
support for no-web syntax

### ISSUE THREAD

**Issue by jhelberg** [darold/pgFormatter#21]
I'm using lots of SQL-code inside org-mode documents which re-use SQL-snippets in a no-web fashion:
E.g. `SELECT * FROM projects WHERE projectnumber in <<internalprojects>>;`
The internalprojects thingy is converted into `<< internalprojects >>` (with blanks as << and >> are recognized as bit-shift operators) by pgFormatter and ends up not being expanded when I tangle or execute the code from org-babel.
Is it an idea to add an option to keep no-web syntax intact?

I'm using the following code-snippet for formatting sql code-blocks hitting Shift-F4; I would rather use an option for pg_format than twice sed:

`(global-set-key [S-f4] (lambda () (interactive)  (progn (org-babel-mark-block) (shell-command-on-region (region-beginning) (region-end) "pg_format | sed 's/<< /<</g' | sed 's/ >>/>>/g'" t t) )))`

**Comment by darold** [comment]
Hi,

Commit ab66339 add this feature. From documentation:

Prevent replacing code snippets

Using -p or --placeholder command line option it is possible to keep code
untouched by pgFormatter in your SQL queries. For example, in query like:

        SELECT * FROM projects WHERE projectnumber
                IN <<internalprojects>> AND username = <<loginname>>;

you may want pgFormatter to not interpret << and >> as bit-shift keywords
and modify your code snippsets. You can use a Perl regular expression to
instruct pgFormatter to keep some part of the query untouched. For example:

        pg_format samples/ex9.sql -p '<<(?:.*)?>>'

will not format the bit-shift like operators.

Best regards,

**Comment by jhelberg** [comment]
thx, i'll test this soon.

**Comment by jhelberg** [comment]
-p confirmed as a great option
