### ISSUE TITLE
Extra changing case of values in some cases

### ISSUE THREAD

**Issue by allprecisely** [darold/pgFormatter#210]
Hi! I faced with some other problems :) I highlighted values with **value**, which should be lowercase:
 
1) `INSERT INTO table1 (value1, login) VALUES (23, 'sth');`
```
INSERT INTO table1 (value1, **LOGIN**)
    VALUES (23, 'sth');
```

2)` ALTER TABLE table1 ALTER COLUMN location SET NOT NULL;`
```
ALTER TABLE table1
    ALTER COLUMN **LOCATION** SET NOT NULL;
```

3) `CREATE TYPE type1 AS (cluster TEXT);`
```
CREATE TYPE type1 AS (
    **CLUSTER** TEXT
);
```

4) `select hash from table1 group by hash;`
```
SELECT
    **HASH**
FROM
    table1
GROUP BY
    **HASH**;
```

5) `CREATE TABLE table1 (name TEXT NOT NULL, type varchar(255) NOT NULL, primary key (name));`
```
CREATE TABLE table1 (
    name TEXT NOT NULL,
    **TYPE** varchar(255) NOT NULL
    PRIMARY KEY (**NAME**)
);
```

6) ALTER TABLE biometry_etalons.media DROP COLUMN type;...

7) `CREATE INDEX value1 ON value2 (key, value);`
`CREATE INDEX value1 ON value2 (**KEY**, value);`

8) `SELECT rule.type AS type FROM table1.rule rule;`
```
SELECT
    rule.type AS **TYPE**
FROM
    table1.rule **RULE**;
```

9) `CREATE TABLE table1 (some_login VARCHAR(16), type VARCHAR(16) NOT NULL, UNIQUE (some_login, type));`
```
CREATE TABLE table1 (
    some_login varchar(16),
    **TYPE** VARCHAR(16) NOT NULL,
    UNIQUE (some_login, **TYPE**)
);
```

Thank you!

**Comment by darold** [comment]
Commits 8e6c93c and 5ff4f95 fix all these false positive keywords detection.
