### ISSUE TITLE
Publish docker image to Docker hub

### ISSUE THREAD

**Issue by gajus** [darold/pgFormatter#211]
Would be nice to have it curated by the same author, rather than one of many random forks.

**Comment by darold** [comment]
Sorry but I don't have time to maintain such image, I guess that people who use it can create or provide their own image.

**Comment by wwuck** [comment]
Hi @darold, you can do a one-time setup for automated building with docker hub so docker hub will automatically trigger a new docker image build/release when you push commits to github.  After this is easily setup, you shouldn't need to touch anything.

https://betterprogramming.pub/build-your-docker-images-automatically-when-you-push-on-github-18e80ece76af

**Comment by AndreMiras** [comment]
Agree on that @wwuck, since the Dockerfile is already there, the only thing missing is to point DockerHub to this repo and it would build & publish a new image on new commits.
@darold would you reconsider, it's a rather low hanging fruit and it's very useful
