### ISSUE TITLE
[Feature request] Format RLS policy definitions as separate statement

### ISSUE THREAD

**Issue by madflow** [darold/pgFormatter#212]
Given:

```SQL
CREATE POLICY fp_s ON information FOR SELECT
  USING (group_id <= (SELECT group_id FROM users WHERE user_name = current_user))
```

Current output  from website (http://sqlformat.darold.net/) with "alternate formatting":

```SQL
CREATE POLICY fp_s ON information
    FOR SELECT
        USING (group_id <= ( SELECT group_id
        FROM
            users
        WHERE
            user_name = CURRENT_USER))
```

The indention/formatting is okayish. But - the `FROM/WHERE` definitions are formatted like they would belong to the `USING` column.

Desired output something along the line:

```SQL
CREATE POLICY fp_s ON information 
    FOR SELECT
        USING (group_id <= (
                SELECT
                    group_id
                FROM
                    users
                WHERE
                    user_name = CURRENT_USER))
```

The above was created just by copy and pasting the `USING` part into the formatting window.

The same would apply to `WITH CHECK`.

**Comment by darold** [comment]
Commit 5bbc0a8 fixes this formatting using alternate formatting. I think I will apply this formatting by default without having to use the alternative as default format is broken when there is a sub query. A fix to keep everything in the same line is not useful in sub query case.

Online demo site updated.

**Comment by madflow** [comment]
@darold Thanks, very nice!
