### ISSUE TITLE
Add option to preserve empty newlines

### ISSUE THREAD

**Issue by svenklemm** [darold/pgFormatter#216]
It would be nice to have an option to preserve empty newlines between consecutive comment blocks like the following:
```
-- block 1
-- block 1

-- block 2
-- block 2
```

**Comment by darold** [comment]
Won't be done, too much work and complicated or something that is not really valuable in my opinion. The solution is to add a -- between the two comments.

**Comment by mfridman** [comment]
I know it's an old issue, but figured I'd drop another case for this. Some tools add license headers and comment directives to the SQL files, and it'd be a nice property if these could be preserved.

E.g.,

```sql
-- +migrate up
-- start
CREATE INDEX ON foo (id);
CREATE INDEX ON bar (id);
--end

-- +migrate down
-- start
DROP INDEX IF EXISTS foo_id_idx;
DROP INDEX IF EXISTS bar_id_idx;
-- end 
```

And ideally there'd be some way to preserve the outer comment structure, treating them as blocks like OP suggested.
