### ISSUE TITLE
Some operator names get mangled

### ISSUE THREAD

**Issue by laurenz** [darold/pgFormatter#22]
You fixed a couple of operators in commit 2e0417e72e64b0c013efc5200453c79828e06834, but there are still some missing:

<table>
<tr><th>operator</th><th>meaning</th></tr>
<tr><td><tt>-|-</tt></td><td>range operator "is adjacent to"</td></tr>
<tr><td><tt>#&lt;</tt><br><tt>#&lt;=</tt><br><tt>#&gt;=</tt><br><tt>#&lt;&gt;</tt><br><tt>#=</tt></td><td>compares <tt>tinterval</tt> and <tt>reltime</tt></td></tr>
<tr><td><tt>&lt;#&gt;</tt></td><td><tt>abstime</tt> to <tt>tinterval</tt> conversion operator</td></tr>
<tr><td><tt>&lt;?&gt;</tt></td><td><tt>abstime</tt> is contained by <tt>tinterval</tt></td></tr>
<tr><td><tt>?#</tt><br><tt>?-</tt><br><tt>?||</tt><br><tt>?|</tt><br><tt>?-|</tt><br><tt>&amp;&lt;|</tt><br><tt>##</tt></td><td>various geometric operators</td></tr>
<tr><td><tt>~~</tt><br><tt>!~~</tt><br><tt>~~*</tt><br><tt>!~~*</tt></td><td><tt>LIKE</tt> operators</td></tr>
<tr><td><tt>!~</tt><br><tt>~*</tt><br><tt>!~*</tt></td><td>regular expression operators</td></tr>
<tr><td><tt>!!</tt></td><td>deprecated factorial operator</td></tr>
<tr><td><tt>|/</tt><br><tt>||/</tt></td><td>square root and cube root</td></tr>
<tr><td><tt>&gt;&gt;=</tt><br><tt>&lt;&lt;=</tt></td><td><tt>inet</tt> operators</td></tr>
<tr><td><tt>~&lt;=~</tt><br><tt>~&gt;=~</tt><br><tt>~&gt;~</tt><br><tt>~&lt;~</tt></td><td>string comparison for pattern matching operator families</td></tr>
<tr><td><tt>*=</tt><br><tt>*&gt;</tt><br><tt>*&lt;&gt;</tt><br><tt>*&lt;</tt><br><tt>*&lt;=</tt><br><tt>*&gt;=</tt></td><td>composite type comparison operators</td></tr>
<tr><td><tt>@@@</tt></td><td>deprecated full text search operator</td></tr>
</table>

**Comment by darold** [comment]
Thanks, this might be fixed  in commit 2627a84.

**Comment by laurenz** [comment]
I tested a few, and it looks fine.  Thanks!
