### ISSUE TITLE
Sources using COPY … FROM stdin are mangled

### ISSUE THREAD

**Issue by paulmelnikow** [darold/pgFormatter#222]
Hi there, and thanks for this useful tool!

I've generated some SQL using pg_dump which I'd like to format. The SQL is using the `COPY … FROM stdin` format. When I run it through pgFormatter it gets mangled.

Example input:

```sql
COPY public.subjects (id, name, gender, dataset_id) FROM stdin;
1	subject1	F	1
2	subject2	F	1
3	subject3	F	1
\.
```

Output:

```sql
COPY public.subjects (id, name, gender, dataset_id)
FROM
    stdin;

1 subject1 F 1 2 subject2 F 1 3 subject3 F 1.
```

Another example:

```sql
COPY public.datasets (id, name, units, reference_frame_up, reference_frame_look) FROM stdin;
1	2020-09-19	cm	{0,1,0}	{0,0,1}
\.
```

Output:

```sql
COPY public.datasets (id, name, units, reference_frame_up, reference_frame_look)
FROM
    stdin;

1 2020 - 09 - 19 cm {0,
1,
0 } {0,
0,
1 }.
```

This is using pg_format 4.4.

**Comment by darold** [comment]
Commit 5690b24 might fix this regression in COPY formatting. Thanks for the report.

**Comment by paulmelnikow** [comment]
Amazing! Wow, thank you so much!
