### ISSUE TITLE
Issue with Create Temporary Table

### ISSUE THREAD

**Issue by prichardson211** [darold/pgFormatter#224]
Hi,

Once again I love your work.  Thanks for doing such an awesome job.  I found an odd use case.

Here is the query without the CREATE TEMPORARY TABLE:
```
CREATE TEMPORARY TABLE tt_monthly_data AS
WITH a1 AS (
    SELECT
        *
    FROM
        test1
)
SELECT
    ROUND(AVG(t1)) avg_da,
    ROUND(AVG(t2))
FROM
    a1;
```

Here it is with the CREATE TEMPORARY TABLE:
```
CREATE TEMPORARY TABLE tt_monthly_data AS
WITH a1 AS (
    SELECT
        *
    FROM
        test1
)
SELECT
    ROUND (
AVG(t1)) avg_da,
    ROUND (
AVG(t2))
FROM
    a1;
```

**Comment by darold** [comment]
Thanks for the report and the encouragements, commit  625f75a might fix this issue.
