### ISSUE TITLE
Floats with signed exponents (like 1e-5) are formatted incorrectly

### ISSUE THREAD

**Issue by jakob** [darold/pgFormatter#226]
IEEE floats in exponential notation with negative or explicit positive exponents are formatted incorrectly.

If you format the following query:
```sql
select 1e-5, 1e+5;
```

The result is:
```sql
SELECT
    1e - 5,
    1e + 5
```

This results in a syntax error.

**Comment by jakob** [comment]
I'm not sure how much effort fixing this issue is, but since we are using your library in a commercial product, I can offer to pay a bounty of 200€ for fixing this bug. If that sounds like a fair deal, please email me at jakob@eggerapps.at to discuss details.

**Comment by darold** [comment]
I see `-` or `+` are taken as operators, I will fix that.

About supporting pgFormatter if you want you can make a [donation](https://www.paypal.com/donate/?hosted_button_id=P225RHBSFP824) , I have also added a Donation button on pgFormatter official site http://sqlformat.darold.net/

**Comment by darold** [comment]
Commit 2797465 fixes this issue.
