### ISSUE TITLE
CREATE TABLE formatted to single line with quoted schema

### ISSUE THREAD

**Issue by robx** [darold/pgFormatter#227]
Without quotes, we have

```sql
CREATE TABLE public.sample (
    a integer,
    b integer,
    c integer)
```

If we quote the schema (`CREATE TABLE "public".sample ...`), we get

```sql
CREATE TABLE "public".sample (a integer, b integer, c integer)
```

instead of the expected multi-line version above (with quotes).

Incidentally, quoting the table name introduces a strange space: `CREATE TABLE public."sample" ...` becomes

```sql
CREATE TABLE public. "sample" (
    a integer,
    b integer,
    c integer)
```

This is with pg_format version 4.4 installed through nix.

**Comment by darold** [comment]
I don't know why this problem was not caught before, the use of quote might not be so common. However commit eadb263 might solve this issue and a regression test was added.
