### ISSUE TITLE
Escaping character gets formatted incorrectly and causes syntax error

### ISSUE THREAD

**Issue by clijunky** [darold/pgFormatter#23]
If a string in a query is escaped (e.g. E'This is some text'), a whitespace is placed in between the E and the ' character.  This causes a syntax error on subsequent runs.

**Comment by darold** [comment]
Hi,

Commit 33b413b might fix the issue. Thanks for the report.

Best regards,

**Comment by clijunky** [comment]
Tested good.  Thank you.
