### ISSUE TITLE
Turn off formatting for a section of code

### ISSUE THREAD

**Issue by okomestudio** [darold/pgFormatter#232]
It would be nice if there is a way to turn off a section of code from being formatted. For example, for a code like this:

```sql
...
    WHERE
        ...
        -- pgfmt: off
        AND t1 BETWEEN s1 AND s2
        AND t2 BETWEEN s1 AND s2
        AND t3 BETWEEN s1 AND s2
        -- pgfmt: on
        ...
```

the enclosed section is left as is and won't get formatted.

If there already is a way to do something like this, I'd appreciate it if someone could let me know.

**Comment by darold** [comment]
Maybe you should look at option `-p`:
```
    -p | --placeholder RE : set regex to find code that must not be changed.
```
With you example it could be something like that:
```
pg_format  -p '-- pgfmt: off(?:.*)?-- pgfmt: on' file_to_format.sql
```
there is an other example in the documentation.

**Comment by okomestudio** [comment]
Thank you very much for a quick response!

Unfortunately the regex doesn't appear to work. I haven't looked at Perl for a long time so I may be way off base, but is the regex aware of multi-line search and replace? I'm looking at a place like this:

https://github.com/darold/pgFormatter/blob/master/lib/pgFormatter/Beautify.pm#L300

If this works as intended, the ``-p`` switch does seem like what I need.

**Comment by darold** [comment]
Sorry I was sure that it was multi-line, however I have added a new command line option in commit 3aff86f to allow multi-line placeholder.
```
    -M | --multiline      : enable multi-line search for -p or --placeholder.
```

so your command will be:
```
pg_format -M  -p '-- pgfmt: off(?:.*)?-- pgfmt: on' file_to_format.sql
```

**Comment by darold** [comment]
I I use this query to be formatted:
```
SELECT * FROM
    WHERE
        t0 = 'DDDDD'
                -- pgfmt: off
                AND t1 BETWEEN s1 AND s2
                AND t2 BETWEEN s1 AND s2
                AND t3 BETWEEN s1 AND s2
                -- pgfmt: on
        ORDER BY 1;

```
I obtain the following:
```
SELECT
    *
FROM
WHERE
    t0 = 'DDDDD' -- pgfmt: off
		AND t1 BETWEEN s1 AND s2
		AND t2 BETWEEN s1 AND s2
		AND t3 BETWEEN s1 AND s2
		-- pgfmt: on
ORDER BY
    1;
```
The part that match the regexp is not formatted.

What is the query you want to format?

**Comment by okomestudio** [comment]
That does indeed work for me now. 

I guess if I were to nitpick, it might be somewhat counter intuitive that the placeholder marker (i.e., ``-- pgfmt: off`` in this case) itself can be affected by the formatting. That's a minor point and there might be a clever regex that might prevent it from happening. Need to explore a bit.

Thank you very much for the quick responses and the fix!

**Comment by peterwicksstringfield** [comment]
Minor nitpick: I think you want a non-greedy wildcard:

```
pg_format -M  -p '-- pgfmt: off(?:.*?)?-- pgfmt: on' file_to_format.sql
```

(Thanks for the formatter!)
