### ISSUE TITLE
Sometimes $HOME variable doesn't exist on windows

### ISSUE THREAD

**Issue by hmble** [darold/pgFormatter#233]
Script is showing error message like

`Uncaught exception: Use of uninitialized value $ENV{"HOME"} in concatenation`

In [linked issue](https://github.com/bucardo/check_postgres/issues/23) there's a sam e issue of assuming $HOME exists by default, I guess the reason is that the script assumes that `$HOME` always exist

[heres the line using $HOME variable](https://github.com/darold/pgFormatter/blob/3aff86f3fe8e9fb7ffc823e2407177474c59000a/lib/pgFormatter/CLI.pm#L351) 

```diff
-  $cfg{ 'config' } //= "$ENV{HOME}/.pg_format"
+  $cfg{ 'config' } //= "exists $ENV{HOME} and $ENV{HOME}/.pg_format"
```

is this correct fix ?

**Comment by darold** [comment]
No, I would use something like:
```
cfg{ 'config' } //= (exists  $ENV{HOME}) ? "$ENV{HOME}/.pg_format" : ".pg_format";
```

**Comment by hmble** [comment]
Soo should I make PR with this change ? I don't know anything about perl but I can just change the line with your suggested code.

**Comment by darold** [comment]
Yes please make a PR.
