### ISSUE TITLE
pgFormatter mangles multi-line strings

### ISSUE THREAD

**Issue by jbeard4** [darold/pgFormatter#235]
Please consider the following reduced example of formatting multi-line strings with pgFormatter:

```sql
create table test;

comment on table test is
  E'foo\n'
  'bar\n'
  'bat';
```

pgFormatter yields:

```sql
CREATE TABLE test;

COMMENT ON TABLE test IS E'foo\n' 'bar\n' 'bat';
```

Which is not valid SQL according to the Postgresql manual [here](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS): 

```
SELECT 'foo'      'bar';
is not valid syntax. (This slightly bizarre behavior is specified by SQL; PostgreSQL is following the standard.)
```

Thank you for your time and attention to this issue.

**Comment by darold** [comment]
Commit ac71863 might fixes this issue.

**Comment by paulmelnikow** [comment]
Thanks so much for addressing this so quickly!

**Comment by jbeard4** [comment]
Yes, thanks so much for your prompt help with this. I will test this and report back to you shortly to confirm the fix.

**Comment by jbeard4** [comment]
Hi @darold , I can confirm that commit ac71863 fixes this issue. Thanks again for your help with this!
