### ISSUE TITLE
Problem handling NOT after AND

### ISSUE THREAD

**Issue by chris-mthomas** [darold/pgFormatter#236]
In a SQL WHERE clause where you have a series of AND conditions followed by parentheses the indentation works fine but when I introduce a NOT after the AND and before the first paranthesis, e.g.  `AND NOT (` the indentation of following lines, lines up with the NOT rather than the parenthesis

e.g. this WHERE clause will not format correctly with the NOTs in place:

`WHERE
    a_ledger_number_i = param.LedgerNumber
    AND a_import_successful_l = TRUE
    AND a_calendar_year_i = param.CalendarYear
    AND a_period_number_i = param.PeriodNumber
    AND a_batch_number_i > 0
    AND NOT( a_run_number_i = 0
    AND param.RunNumber > 0
    AND ( ( a_income_total_n + a_expense_total_n ) <> ( param.IncomeTotal + param.ExpenseTotal )
    OR a_xfer_total_n <> param.XferTotal ) )
    AND NOT( a_run_number_i > 0
    AND param.RunNumber > 0
    AND a_run_number_i <> param.RunNumber )`

**Comment by darold** [comment]
What are you expecting as final format? Actually I don't see any formatting problem with the following output:
```
SELECT
    *
FROM
    param
WHERE
    a_ledger_number_i = param.LedgerNumber
    AND a_import_successful_l = TRUE
    AND a_calendar_year_i = param.CalendarYear
    AND a_period_number_i = param.PeriodNumber
    AND a_batch_number_i > 0
    AND NOT (a_run_number_i = 0
        AND param.RunNumber > 0
        AND ((a_income_total_n + a_expense_total_n) <> (param.IncomeTotal + param.ExpenseTotal)
            OR a_xfer_total_n <> param.XferTotal))
    AND NOT (a_run_number_i > 0
        AND param.RunNumber > 0
        AND a_run_number_i <> param.RunNumber);
```

**Comment by chris-mthomas** [comment]
It should be:


SELECT

    *

FROM

    param

WHERE

    a_ledger_number_i = param.LedgerNumber

    AND a_import_successful_l = TRUE

    AND a_calendar_year_i = param.CalendarYear

    AND a_period_number_i = param.PeriodNumber

    AND a_batch_number_i > 0

    AND NOT (a_run_number_i = 0

             AND param.RunNumber > 0

             AND ((a_income_total_n + a_expense_total_n) <> (param.IncomeTotal + param.ExpenseTotal)

                  OR a_xfer_total_n <> param.XferTotal))

    AND NOT (a_run_number_i > 0

             AND param.RunNumber > 0

             AND a_run_number_i <> param.RunNumber);

**Comment by darold** [comment]
I don't see differences with the output I have reported, maybe you were using and old version before posting the last not. Closing.
