### ISSUE TITLE
Add option for not having space after function call

### ISSUE THREAD

**Issue by amerryma** [darold/pgFormatter#237]
Current:
```sql
DROP FUNCTION IF EXISTS app_public.hello (a text);
```

Expected:
```sql
DROP FUNCTION IF EXISTS app_public.hello(a text);
```

**Comment by darold** [comment]
I'm not in favor of adding a new option just for that, I will be more interested in simply removing this space character as this is the default behavior in a PostgreSQL formatting. The problem is that it will break backward compatibility but it could be justified here.

**Comment by amerryma** [comment]
> I'm not in favor of adding a new option just for that, I will be more interested in simply removing this space character as this is the default behavior in a PostgreSQL formatting. The problem is that it will break backward compatibility but it could be justified here.

Ok, makes sense. On another note, I've been using DataGrip for formatting right now and it has that toggle. I'm sure they are using something completely

**Comment by darold** [comment]
Ok I will add this option.

**Comment by darold** [comment]
Commit 277f9b4 adds this feature. See option --no-space-function.
