### ISSUE TITLE
exception with output file

### ISSUE THREAD

**Issue by adunstan** [darold/pgFormatter#238]
andrew@ub20:~ $ pg_format --version
pg_format version 4.4
andrew@ub20:~ $ echo 'select foo from bar' | pg_format -o foo.sql -
Uncaught exception: Deadly warning: Filehandle STDIN reopened as $_[...] only for output at (eval 8) line 149.
 at /usr/bin/pg_format line 27.
	main::__ANON__("Filehandle STDIN reopened as \$_[...] only for output at (eval"...) called at (eval 8) line 149
	pgFormatter::CLI::__ANON__(GLOB(0x55a8169477b8), ">", "foo.sql") called at /usr/share/perl5/pgFormatter/CLI.pm line 157
	pgFormatter::CLI::save_output(pgFormatter::CLI=HASH(0x55a816676cd0)) called at /usr/share/perl5/pgFormatter/CLI.pm line 73
	pgFormatter::CLI::run(pgFormatter::CLI=HASH(0x55a816676cd0)) called at /usr/bin/pg_format line 49
 at /usr/bin/pg_format line 19.
	main::__ANON__("Deadly warning: Filehandle STDIN reopened as \$_[...] only for"...) called at /usr/share/perl/5.30/Carp.pm line 292
	Carp::confess("Deadly warning: Filehandle STDIN reopened as \$_[...] only for"...) called at /usr/bin/pg_format line 27
	main::__ANON__("Filehandle STDIN reopened as \$_[...] only for output at (eval"...) called at (eval 8) line 149
	pgFormatter::CLI::__ANON__(GLOB(0x55a8169477b8), ">", "foo.sql") called at /usr/share/perl5/pgFormatter/CLI.pm line 157
	pgFormatter::CLI::save_output(pgFormatter::CLI=HASH(0x55a816676cd0)) called at /usr/share/perl5/pgFormatter/CLI.pm line 73
	pgFormatter::CLI::run(pgFormatter::CLI=HASH(0x55a816676cd0)) called at /usr/bin/pg_format line 49

**Comment by darold** [comment]
Good catch, thanks Andrew. Commit 4e4394e fixes this issue.

**Comment by adunstan** [comment]
fix confirmed
