### ISSUE TITLE
idea: do not add line breaks after enumeration in group by

### ISSUE THREAD

**Issue by pfassina** [darold/pgFormatter#239]
I often use enumeration in my group by statements, similar to what is shown below:

```sql
select
  state
  , city
  , sum(units) as sales
from orders
group by 1, 2
```

When I run pgFormatter, it breaks down the enumaration in multiple lines:
```sql
select
  state
  , city
  , sum(units) as sales
from orders
group by
  1
  , 2
```

It would be very cool if pgFormatter were to keep my group by enumaration in a single line, rather than breaking it down into multiple lines.

**Comment by darold** [comment]
Commit 2babb5a keep enumeration in GROUP BY clause on a single line when option -t | --format-type is used.
