### ISSUE TITLE
Project local .pg_format configuration

### ISSUE THREAD

**Issue by lithammer** [darold/pgFormatter#250]
It would be nice if `pg_format` looked in the current directory for a `.pg_format` config file before `~/.pg_format`.

Or even better would be if it started searching relative to the file-to-be-formatted and searched upwards recursively until it finds a `.pg_format`, stopping at `~/`. And `stdin` could default to current working directory instead.

So given `cwd = ~/foo/bar` and `filepath = ../baz/some_file.sql`, use `filepath` directory as starting point:

1. `~/foo/bar/baz/.pg_format`
2. `~/foo/bar/.pg_format`
3. `~/foo/.pg_format`
4. `~/.pg_format`

And using `filepath = stdin`, use `cwd` as starting point:

1. `~/foo/bar/.pg_format`
2. `~/foo/.pg_format`
3. `~/.pg_format`

**Comment by darold** [comment]
Commit a4e83ba adds local .pg_format to be used instead of ~/.pg_format if present. For other places best is to use the --config option.

**Comment by lithammer** [comment]
Thanks! 👍
