### ISSUE TITLE
Docker - /usr/bin/env: 'perl\r': No such file or directory

### ISSUE THREAD

**Issue by rr0001** [darold/pgFormatter#252]
I followed the instructions for using with Docker and it wasn't working due to the location of the perl bin in the `pg_format` shebang. I was able to fix it by changing it to:

`#!/usr/local/bin/perl`

I can submit a pull request if you like.

Thanks for your project.

**Comment by darold** [comment]
Well the shebang have been changed to `#!/usr/bin/env perl` to comply with different installation path. If by pull request you mean adding the information to the documentation, yes please.

**Comment by rr0001** [comment]
Looks like my issue was caused due to the `pg_format` file using CRLF line endings. After changing to LF in VSCode and rebuilding the image, it works properly. My apologies.
