### ISSUE TITLE
Support for psql meta commands

### ISSUE THREAD

**Issue by tbussmann** [darold/pgFormatter#26]
If you try to run psql script through pgFormatter, all the meta commands gets messed up. It would be great if pgFormatter could learn to ignore lines starting with an backslash and would detect execution commands. For this we would have to match something like the following expression `(\\(g(set|exec|x)+|watch.*|crosstabview.*))$` and treat the match like a `;`

**Comment by darold** [comment]
Current development code detect psql meta command as follow:
```
/^\\(set|unset|i|c|encoding|prompt|timing|setenv|cd|conninfo|password|connect|lo_export|lo_import|lo_list|lo_unlink)$/
```
I will add other keywords.

**Comment by darold** [comment]
Changes have been pushed and applied in commit c259c32 where main feature is a plpgsql beautifier.
I will add other psql meta command coming with pg 10.0 asap.

**Comment by darold** [comment]
Added in commit 5afe369

**Comment by tbussmann** [comment]
I've updated the PR to correct my misunderstanding that not all meta commands do separate statements. Now even things like the following can be processed:
```
\set a 2 \\ Select  :a, \unset a \\ b, FROM  c \gx
```

**Comment by phiresky** [comment]
Just found this issue, seems like \include_relative should work but doesn't, see https://github.com/darold/pgFormatter/issues/174
