### ISSUE TITLE
Add custom formatting for json_build_object()

### ISSUE THREAD

**Issue by luukvhoudt** [darold/pgFormatter#261]
Currently the build-in `json_build_object()` function is treated like any other function. However this function usually contains a lot of arguments and thus will get unreadable quickly when maintaining regular function formatting.

I would like to suggest to apply custom formatting to the `json_build_object()` as shown in the expected behavior below.

# Expected behavior

```sql
select
  json_build_object(
    'foo', 'bar',
    'nested', json_build_object(
      'hello', 'world'
    )
  ) as col1,
  'hello world' as col2;
```

# Actual behavior

```sql
select json_build_object('foo', 'bar', 'nested', json_build_object('hello', 'world')) as col1, 'hello world' as col2;
```

**Comment by darold** [comment]
pgFormatter is used to format the SQL and plpgsql, formatting of json or other constant is not in the scope.
