### ISSUE TITLE
The v5.1 tag doesn't actually contain the 5.1 release

### ISSUE THREAD

**Issue by tao-cumplido** [darold/pgFormatter#263]
https://github.com/darold/pgFormatter/blob/v5.1/pg_format#L36

I noticed this issue when I installed pgFormatter with homebrew. According to the install log 5.1 should have been installed, naturally I was surprised when `pg_format` would still print 5.0.

The homebrew formula points to this repo's v5.1 tag 
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/pgformatter.rb

**Comment by darold** [comment]
Yes this was a mistake, the version have been fixed in development code. I can not change it in the 5.1 tagged release without republishing.

**Comment by mieszko4** [comment]
I suggest releasing `v5.1.1` or `v5.2` with changelog simply mentioning that mistake.

**Comment by darold** [comment]
Version 5.2 have just been published.
