### ISSUE TITLE
Anonymize doesn't seem to be working with the latest version

### ISSUE THREAD

**Issue by nponiros** [darold/pgFormatter#265]
`echo "select 'b'" | ./pg_format --anonymize` with version 4.4 returns

```
SELECT
    'tA2ZUMwbPX'
```

With version 5 it returns

```
SELECT
    'b'
```
https://sqlformat.darold.net/ with "Anonymize values in queries" checked also returns the query with 'b' in it.

**Comment by darold** [comment]
Fixed in commit d9df505, thanks for the report.
