### ISSUE TITLE
Example syntax for ~/.pg_format config file

### ISSUE THREAD

**Issue by ianyepan** [darold/pgFormatter#266]
I would like to put some basic configurations in the global config file (things like 2-space indentation etc.). What is the expected syntax of this file? I was looking for an example but couldn't find any. Thanks!

**Comment by darold** [comment]
There is a sample configuration file in the doc sub directory, see [here](https://github.com/darold/pgFormatter/blob/master/doc/pg_format.conf.sample)

**Comment by ianyepan** [comment]
Thanks! Got it to work.
