### ISSUE TITLE
Using materialized view storage parameters break formatting

### ISSUE THREAD

**Issue by wilsonzlin** [darold/pgFormatter#271]
When creating a standard materialized view, pgFormatter works great:

<table>
<tr>
<th>Input</th>
<th>Formatted</th>
</tr>
<tr>
<td>
<pre>
create materialized view v as
select
  sum(x) as x,
  sum(y) as y,
  sum(z) as z
from
  t;
</pre>
</td>
<td>
<pre>
CREATE MATERIALIZED VIEW v AS
SELECT
    sum(x) AS x,
    sum(y) AS y,
    sum(z) AS z
FROM
    t;
</pre>
</td>
</tr>
</table>

However, when using storage parameters, the formatting breaks:

<table>
<tr>
<th>Input</th>
<th>Formatted</th>
</tr>
<tr>
<td>
<pre>
create materialized view v with (storage_param=1) as
select
  sum(x) as x,
  sum(y) as y,
  sum(z) as z
from
  t;
</pre>
</td>
<td>
<pre>
CREATE MATERIALIZED VIEW v WITH ( storage_param = 1
) AS
SELECT
    sum(
        x
) AS x,
    sum(
        y
) AS y,
    sum(
        z
) AS z
FROM
    t;
</pre>
</td>
</tr>
</table>

**Comment by darold** [comment]
Commit dffa2b5 fixes this issue. Thanks.

**Comment by wilsonzlin** [comment]
Thanks @darold!
