### ISSUE TITLE
Bad indentation when a column is named "index"

### ISSUE THREAD

**Issue by marco44** [darold/pgFormatter#272]
When a column is named index, sometimes it messes up with indentation

Here is a case when index doesn't throw pgformatter off track:
```
pg_format << EOF
select a, index from t2
EOF
SELECT
    a,
    INDEX
FROM
    t2
```
But this query does. When the column isn't named "index", all is good:
```
pg_format << EOF
select t1.a, (select foo from t2) from t1
EOF
SELECT
    t1.a,
    (
        SELECT
            foo
        FROM
            t2)
FROM
    t1
```
But if the column is named "index", it's not. Of course this is simplified, my case is much worse, as there are several instances of a column named "index".
```
pg_format << EOF
select t1.a, (select index from t2) from t1
EOF
SELECT
    t1.a,
    (
        SELECT
            INDEX
        FROM
            t2)
    FROM
        t1
```

**Comment by darold** [comment]
Commit 53b7638 fixes this issue.
