### ISSUE TITLE
Detecting JSON operator as invalid

### ISSUE THREAD

**Issue by vidocco** [darold/pgFormatter#275]
Hi,

We currently have an sql file that contains the following bit of SQL: 
```
CASE WHEN "something" ?| "someKey" THEN
```
When running pgFormatter through this file, it automatically changes `?|` into `? |` (which is not the same [operator](https://www.postgresql.org/docs/11/functions-json.html)).

**Comment by darold** [comment]
Commit 343047e fixes this issue.

**Comment by bbstilson** [comment]
I'm encountering a similar issue with the `#-` operator. It might be best to add all the missing operators from the [docs](https://www.postgresql.org/docs/11/functions-json.html).

```
#-
-
||
?&
?|
?
<@
@>
#>>
#>
->>
->
```
