### ISSUE TITLE
Keywords are processed too greedily

### ISSUE THREAD

**Issue by SebAlbert** [darold/pgFormatter#28]
For some words it depends on the context whether they are what they seem to be if viewed in isolation.

For example, in the Postgres operator on compound data types (rows), `IS DISTINCT FROM` (or `IS NOT DISTINCT FROM`), the word `FROM` is certainly not the one structuring the entire statement as in `SELECT ... FROM ... WHERE`. However, in the formatting result, it is treated as such nevertheless, which yields strange-looking results.

Example query: `SELECT * FROM t WHERE a IS NOT DISTINCT FROM b`
(assuming there are columns `a` and `b` of the same composite type in table `t`).

**Comment by rbovard** [comment]
Same kind of issue with `SELECT` in `GRANT SELECT ON TABLE ...`

**Comment by darold** [comment]
Commit 8a7c2ae remove newline between DISTINCT and FROM.

**Comment by darold** [comment]
@rbovard commit adc5ab1 might fix the issue on GRANT reported in issue #29

**Comment by rbovard** [comment]
@darold Thanks, that was quick!

**Comment by SebAlbert** [comment]
Looks good, thanks
