### ISSUE TITLE
Wrong wrapping in create table

### ISSUE THREAD

**Issue by alehaa** [darold/pgFormatter#280]
If there are comments in `CREATE TABLE`, the column definition following the comment won't be wrapped and placed at the same line as the previous column.

```SQL
CREATE TABLE IF NOT EXISTS hello
(
  foo char(20) NOT NULL UNIQUE,

  -- A comment
  bar char(25),
  abc integer
);
```

gets

```SQL
CREATE TABLE IF NOT EXISTS hello (
  foo char(20) NOT NULL UNIQUE, bar char(25),
  abc integer
);
```

**Comment by darold** [comment]
This was happening when `--nocomment` was used. Commit 3bd6b91 fixes this issue.
