### ISSUE TITLE
Invalid Multiline String Constant Formatting

### ISSUE THREAD

**Issue by zaneduffield** [darold/pgFormatter#284]
As per the SQL standard, and as documented by Postgres [here](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-CONSTANTS) 

> Two string constants that are only separated by whitespace with at least one newline are concatenated and effectively treated as if the string had been written as one constant.

Currently, pgFormatter will remove the newlines between string constants spread over multiple lines, which produces invalid SQL.

Input
```sql
SELECT 'a'
'b';
```
Output
```sql
SELECT
    'a' 'b'
```

Expected Output
```sql
SELECT
    'a'
    'b';
```

Alternative Expected Output
```sql
SELECT
    'ab';
```

**Comment by darold** [comment]
Commit 5de95ce fixes this issue. Website updated. Code:
```
SELECT 'a'
'b'
'c',
'hello';
```
is now formatted into
```
SELECT
    'a'
    'b'
    'c',
    'hello';
```
