### ISSUE TITLE
PL/pgSQL formatting

### ISSUE THREAD

**Issue by ideev** [darold/pgFormatter#287]
Is it possible to support also PL/pgSQL formatting?
I use your tool for this task, it works! But there are some problems with keywords, which are not the part of SQL.
It would be nice to expand keyword list with PL/pgSQL keywords (`elsif` for example, etc).

**Comment by darold** [comment]
PL/pgSQL formatting is fully supported, what keywords are not supported?

**Comment by ideev** [comment]
For example, `elsif`:
```
if p_val = 'A' then
    l_res := 1;
elsif p_val = 'B' then
    l_res := 2;
end if;
```
I use https://sqlformat.darold.net. When I try to set `keywords` parameter to uppercase, the `elsif` is not recognised as a keyword...

**Comment by darold** [comment]
Right, ELSIF was not present in the keyword list. Commit c0f2483 fixes this issue. I have updated the website too.

**Comment by ideev** [comment]
Thanks, it works! :)
