### ISSUE TITLE
SSL_ERROR_BAD_CERT_DOMAIN on https://sqlformat.darold.net/

### ISSUE THREAD

**Issue by noelleleigh** [darold/pgFormatter#288]
When I visit <https://sqlformat.darold.net/> on Firefox, I get this warning:

> Websites prove their identity via certificates. Firefox Developer Edition does not trust this site because it uses a certificate that is not valid for sqlformat.darold.net. The certificate is only valid for cluster002.hosting.ovh.net.
> 
> Error code: `SSL_ERROR_BAD_CERT_DOMAIN`

**Comment by darold** [comment]
Thanks, I have regenerated the certificate some days ago after the first report but it looks like something has changed at the hosting company. I had to activate ssl certificate for each subdomain, I have fixed that and regenerated the certificate, now it should answer to the sqlformat.darold.net  hostname. Please give it a try and confirm if it is solved at your side.

**Comment by noelleleigh** [comment]
It's working again! Thank you!
