### ISSUE TITLE
GRANT looks terrible when formatted

### ISSUE THREAD

**Issue by vesak** [darold/pgFormatter#29]
Posting
`GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA foo TO role_bar, role_baz;`
to the web formatter produces
```
GRANT
SELECT
,
    INSERT,
    UPDATE
,
        DELETE ON ALL TABLES IN SCHEMA foo TO role_bar,
        role_baz;
```

**Comment by darold** [comment]
Right, just forgot to handle GRANT outside ALL priviledge. Commit adc5ab1 fix that and was applied to online demo so that you can check the output format.
