### ISSUE TITLE
no-space-function isn't always respected

### ISSUE THREAD

**Issue by fenuks** [darold/pgFormatter#303]
I tested this on the latest tagged version (5.4), as well on the latest git version.

This feature is described
> \# Remove the space character between a function call and the open parenthesis that follow.

, but it doesn't work in all cases.

```
$ echo 'SELECT app_public.hello ('test'); DROP FUNCTION IF EXISTS app_public.hello (a text);' | pg_format --no-space-function
SELECT
    app_public.hello (test);

DROP FUNCTION IF EXISTS app_public.hello(a text);
```

**Comment by darold** [comment]
Commit 8758b0e7 fixes this issue.

**Comment by fenuks** [comment]
Thank you!
