### ISSUE TITLE
test psql_crosstab.sql failure: to_char(d, 'Mon') AS "" "month"" name"

### ISSUE THREAD

**Issue by df7cb** [darold/pgFormatter#304]
Hi,

pgformatter 5.4 doesn't pass its tests here:

```
PG_FORMAT=pg_format perl t/regress_test.pl
...
11:49:36 Running test on file t/pg-test-files/sql/psql.sql...
11:49:36 	test ok.
11:49:36 Running test on file t/pg-test-files/sql/psql_crosstab.sql...
11:49:36 	test failed!!!
11:49:36 -    to_char(d, 'Mon') AS """month"" name",
11:49:36 +    to_char(d, 'Mon') AS "" "month"" name",
11:49:36 Running test on file t/pg-test-files/sql/publication.sql...
11:49:37 	test ok.
```

Full build log: https://pgdgbuild.dus.dg-i.net/job/pgformatter-binaries/22/architecture=amd64,distribution=sid/console#console-section-7

**Comment by darold** [comment]
Right, fixed with commit e86c494f.

**Comment by df7cb** [comment]
Thanks! Could you tag a new release with that, or would you prefer to wait?

**Comment by darold** [comment]
I'm traveling to Togo but I will try to fix some other reported issues  during my flight and probably tag a new release this weekend. Thanks Christoph.

**Comment by df7cb** [comment]
Have a nice trip!

**Comment by darold** [comment]
Thanks, release published.

**Comment by df7cb** [comment]
Thanks!
