### ISSUE TITLE
Possible conflict between --wrap-after and --comma-break

### ISSUE THREAD

**Issue by dbachhh** [darold/pgFormatter#318]
Hi, thank you so much for this piece of software. I was playing around with the options and there is a strange case where comma-break doesn't work:

```
pg_format -i test.sql --comma-break --wrap-after 80

INSERT INTO (
    field_one,
    field_two,
    field_three)
VALUES (
    1,
    2,
    3);

pg_format -i test.sql --comma-break

INSERT INTO (
    field_one, field_two, field_three)
VALUES (
    1, 2, 3);
```

So it seems like wrap-after is in conflict comma-break formatting, would like to ask if this the intended behavior ?

**Comment by darold** [comment]
Yes, this is attended. The `--wrap-after` option is used to force a break when a comma is encountered around the 80th characters, in this case the `--comma-break` option can not be used, it has no more sens.
