### ISSUE TITLE
Broken if XDG_CONFIG_HOME is not defined

### ISSUE THREAD

**Issue by looi** [darold/pgFormatter#319]
After 10fc46b5b39dcb1c4bd3196394c11880928ba99a, tool seems broken when XDG_CONFIG_HOME is not defined (e.g. on my mac) with error `Uncaught exception: Use of uninitialized value $ENV{"XDG_CONFIG_HOME"} in concatenation (.) or string`

**Comment by darold** [comment]
Commit 9f482b9 fixes this issue. Thanks.
