### ISSUE TITLE
Node.js thin-wrapper

### ISSUE THREAD

**Issue by gajus** [darold/pgFormatter#32]
@darold Just for your information, I've written a Node.js wrapper for executing `pgFormatter`.

https://github.com/gajus/pg-formatter

**Comment by darold** [comment]
I have downloaded node.js but I don't immediately see how to run your wrapper.

**Comment by gajus** [comment]
If you are not familiar with Node.js, it is going to be tricky, esp. since this is not a CLI, but a library.

Something along the lines of:

```js
npm install pg-formatter

cat <<<'EOF'
const format = require('pg-formatter').format;

console.log(format('SELECT foo FROM bar'));

EOF

```

**Comment by darold** [comment]
I have added a pointer on the pgFormatter documentation about your wrapper, see commit 045fcf0
