### ISSUE TITLE
Function-case and Keyword-case options have duplicate help text.

### ISSUE THREAD

**Issue by Gamrix** [darold/pgFormatter#320]
As the text describing the two options `--function-case` and `--keyword-case` are identical, I don't understand what are the differences between these two options. Could someone explain it? (I am happy to contribute a doc PR if an explanation is provided). 

Text for both are:  `Change the case of the reserved keyword.`

**Comment by darold** [comment]
Hi, thanks for the report. Commit bf6a5de1 fixes this description. Actually the `--function-case` option is use to set the case of the PostgreSQL functions used in a query.
