### ISSUE TITLE
Format a SQL File in place

### ISSUE THREAD

**Issue by bufferclip** [darold/pgFormatter#33]
I want to format a SQL file in place. My idea so far:
`pg_format tmp.sql -o tmp.sql
`
But it does not work, it actually makes the file empty. 

Is it possible to format a SQL file in place?

**Comment by darold** [comment]
You can not do that with pg_format, but it is easy to do with two commands:
```
pg_format file.sql -o tmp.sql
mv tmp.sql file.sql
```

**Comment by francilioaraujo** [comment]
How about adding a -i option for in place formating like sed? I think it would be very usefull

**Comment by darold** [comment]
Even if it was already possible by setting the same output file as the input one, I agree that a dedicated option is more convenient. Commit 38e9187 add option `-i | --inplace`. Thanks.
