### ISSUE TITLE
wrong format for FUNCTION with SET variable FROM current

### ISSUE THREAD

**Issue by bobnil** [darold/pgFormatter#332]
When creating functions, you can specify variables with `SET name FROM CURRENT` to get the value of the parameter that is current when [CREATE FUNCTION](https://www.postgresql.org/docs/current/sql-createfunction.html) is executed.

pg_format is unaware of this syntax and treats FROM as if it were FROM from a query.

```
CREATE FUNCTION name ()
  RETURNS text
  LANGUAGE plpgsql
  SET search_path
FROM
  current
  AS $$
BEGIN
  RETURN 'text';
END;
$$;
```

Expected output:
```
CREATE FUNCTION name ()
  RETURNS text
  LANGUAGE plpgsql
  SET search_path FROM current
  AS $$
BEGIN
  RETURN 'text';
END;
$$;
```

I don't know enough perl to fix it, but by trial and error I found that line 2097 in Beautify.pm has something to do with inserting the line feed:
```
2097         elsif ( $token =~ /^(?:FROM|WHERE|SET|RETURNING|HAVING|VALUES)$/i )
```

**Comment by darold** [comment]
Commit 6ef53a3 fixes this issue.
