### ISSUE TITLE
Formatting breaks when using CTE

### ISSUE THREAD

**Issue by jakob** [darold/pgFormatter#35]
I used the online version to format the following query:

`with one as (select 1 one) select count(one),avg(one) from one`

and it came out like this:

```sql
WITH one AS (
  SELECT
    1 one
)
SELECT
  COUNT(one),
AVG(one)
FROM
  one
```

Note that `AVG` has the wrong indentation. 

If I strip the CTE clause, it looks correct:

```sql
SELECT
  COUNT(one),
  AVG(one)
FROM
  one
```

**Comment by darold** [comment]
Commit 979e149 fix this issue, will update the online site later today. Thanks for the report.

**Comment by darold** [comment]
Demo site updated.
