### ISSUE TITLE
Code formatting to uppercase inconsistencies 

### ISSUE THREAD

**Issue by gienas** [darold/pgFormatter#39]
Tables names: "rule", "template" are transformed to uppercase
e.g 
ALTER TABLE rule -> ALTER TABLE RULE

Data types: bigint, boolean, bytea are not transformed to uppercase.

Column name "name" is transformed to UPPER

Use case command:  pg_format -f 2

P.S Good tool !

**Comment by darold** [comment]
Outside the fact that using reserved keywords as object name is not recommanded I can not find a way to solve this issue. I'm able to fix the above but I'm failing at more complex code like:
```
ALTER TABLE rule RENAME TO template;
ALTER TABLE rule ADD UNIQUE CONSTRAINT template ON blackout;
```
So this will not be solved.
