### ISSUE TITLE
Specifying column 'WITH time zone' causes table formatting to fail

### ISSUE THREAD

**Issue by jamesmbourne** [darold/pgFormatter#45]
As a minimum example, the following SQL is formatted unexpectedly:
```sql
CREATE TABLE demo.test (
    foo text,
    bar timestamp WITH time zone,
    baz text
)
WITH (OIDS = FALSE);
```

The output after applying pg_format is:

```sql
CREATE TABLE demo.test (
    foo text,
    bar timestamp WITH time zone, baz text) WITH (OIDS = FALSE);
```

It appears that `with time zone` fails to be formatted as expected (with each column on a new line). However, using `without time zone` produces the expected result.

**Comment by jamesmbourne** [comment]
Sorry I failed to mention - I encountered this issue in 2.1 as well as 3.0

**Comment by darold** [comment]
Commit 3cbbcbc might solve this issue. Thanks for the report.

**Comment by jamesmbourne** [comment]
@darold I've just pulled down the latest version and can confirm it's now working as expected. Thanks for the quick fix!
