### ISSUE TITLE
When using PREPARE and INSERT formatting fails

### ISSUE THREAD

**Issue by tomhalson** [darold/pgFormatter#47]
As a simple example
```
PREPARE demo AS 
INSERT INTO demo
    VALUES (1, 2, 3, 4);
```
is formatted to 
```
PREPARE demo AS INSERT INTO demo
    VALUES (1, 2, 3, 4);
```

I have tested this with SELECT and UPDATE as well and they are both formatted as expected

```
PREPARE demo AS
SELECT
    *
FROM
    demo;

PREPARE demo AS
UPDATE
    demo
SET
    val = 1;
``` 

This is in version 3.0

**Comment by darold** [comment]
Last commit 778327d might solve this issue. DELETE had the same formatting issue.

**Comment by tomhalson** [comment]
Thanks for the quick fix
