### ISSUE TITLE
Indentdation of INNER JOINS

### ISSUE THREAD

**Issue by winged** [darold/pgFormatter#50]
It seems that `INNER JOIN`s are indented a level too much. See the following fragment (I expect the `INNER JOIN` to be on the same level as the first `LEFT JOIN`. The second LEFT JOIN seems to be correctly indented relative to the previous JOIN statement.. Further INNER JOINs are again indented too much.

```sql
SELECT ...
FROM
    "INSTANCE"
    INNER JOIN "FORM" ON "INSTANCE"."FORM_ID" = "FORM"."FORM_ID"
    LEFT JOIN "FORM_T" ON "FORM"."FORM_ID" = "FORM_T"."FORM_ID"
        AND "FORM_T"."LANGUAGE" = 'de'
        INNER JOIN "INSTANCE_STATE" ON "INSTANCE_STATE"."INSTANCE_STATE_ID" = "INSTANCE"."INSTANCE_STATE_ID"
        LEFT JOIN "INSTANCE_STATE_T" ON "INSTANCE_STATE"."INSTANCE_STATE_ID" = "INSTANCE_STATE_T"."INSTANCE_STATE_ID"
```

**Comment by darold** [comment]
Last commit 7745a05 might solve this issue.

**Comment by winged** [comment]
Awesome! Just tested, looks good now :) Thanks a lot!
