### ISSUE TITLE
bad indentation on case statements

### ISSUE THREAD

**Issue by johndimm** [darold/pgFormatter#52]
Testing with http://sqlformat.darold.net/

-- This one formats correctly.
```
SELECT
    CASE WHEN (FALSE) THEN
        1
    WHEN (TRUE) THEN
        2
    END AS dummy1
FROM
    my_table;
```

-- This one fails to outdent the second WHEN.  Is there a different syntax that works?

```
SELECT
    CASE WHEN (FALSE) THEN
        0
        WHEN (TRUE) THEN
            2
        END AS dummy1
    FROM
        my_table;

```

**Comment by darold** [comment]
Thanks for the report John, commit bd23334 solves this issue.

**Comment by johndimm** [comment]
Great, thanks! When will the fix be released to your online demo?

**Comment by darold** [comment]
Sorry I was not able to connect to the site until now, it is now released on the demo site.
