### ISSUE TITLE
doesn't recognize parenthesized expressions as valid SQL

### ISSUE THREAD

**Issue by dwelle** [darold/pgFormatter#55]
```sql
UPDATE article a
SET title = 'x'
WHERE
	(a.perm & 8)::bool -- breaks its teeth on this
```

At least I assume from:

- http://sqlformat.darold.net/ blowing up
- https://github.com/gajus/pg-formatter which depends on this project not parsing the string

**Comment by darold** [comment]
Thanks for the report, commit 1f7cae1 fixes this issue. Online site updated.
