### ISSUE TITLE
Changelog specifies version 3.1, but pg_format specifies 3.0

### ISSUE THREAD

**Issue by Taytay** [darold/pgFormatter#59]
(First, thanks for pgFormatter! You've saved sanity and bikeshedding for many a SQL programmer)

I probably just caught you at a bad time since you just updated the Changelog 9 hours ago, but I noticed this discrepancy: 

Specifies 3.0:
https://github.com/darold/pgFormatter/blob/master/pg_format#L36

Specifies 3.1:
https://github.com/darold/pgFormatter/blob/master/ChangeLog

**Comment by darold** [comment]
Thanks a lot, I have committed the version change and push a new tag/release. I guess I need some rest now :-)
