### ISSUE TITLE
row level security forces a new line

### ISSUE THREAD

**Issue by madflow** [darold/pgFormatter#60]
Hi!

This is a change request/possible bug report.

This:

```
ALTER TABLE app_public.users ENABLE ROW LEVEL SECURITY;
```

Will always yield after formatting:

```
ALTER TABLE app_public.users ENABLE ROW LEVEL 
SECURITY;
```

I would argue, that this line should be left untouched on one line.

**Comment by darold** [comment]
Commit 747a3b4 fixes that.

**Comment by madflow** [comment]
LGTM! :D Thanks!
