### ISSUE TITLE
no support for postgreSQL 9.5 style named parameter function calls

### ISSUE THREAD

**Issue by snailshell-321** [darold/pgFormatter#61]
In PostgreSQL 9.5 the calling convention of "4.3.2. Using Named Notation" was changed from ":=" to "=>" (both are supported, but the second format is the new default).

The old (pre 9.5-format) ist understood by pgformatter, but the new format isn't.

[example-SELECT-with-function-with-new-named-parameter-style.sql.txt](https://github.com/darold/pgFormatter/files/2431932/example-SELECT-with-function-with-new-named-parameter-style.sql.txt)

The "=>" included in the example is broken into "= >" (space in the middle) which is NOT valid anymore.

**Comment by darold** [comment]
Fixed in commit e6bdfcf. The online site have been updated to latest development change.
