### ISSUE TITLE
DISTINCT and DISTINCT ON should not be treated as prefixes of the first SELECT column

### ISSUE THREAD

**Issue by leorochael** [darold/pgFormatter#65]
The `DISTINCT` and `DISTINCT ON` modifiers of the `SELECT` clause are currently treated by `pg_format` as prefixes of the first column to be selected.

For readability purposes, the `DISTINCT` clause should be treated as a modifier of the whole select clause.

For example a query like:

```
select distinct on (a, b)
a, b, c
from d
order by a, b, c
```

currently gets formatted as:

```
SELECT
    DISTINCT ON (a,
        b) a,
    b,
    c
FROM
    d
ORDER BY
    a,
    b,
    c
```

I think the `SELECT` part should be formatted as:

```
SELECT DISTINCT ON (a, b)
    a,
    b,
    c
```

Or perhaps

```
SELECT
    DISTINCT ON (
        a,
        b)
    a,
    b,
    c
```

Similarly, a query like:

```
select distinct
a, b, c
from d
```

Gets formatted as:

```
SELECT
    DISTINCT a,
    b,
    c
FROM
    d
```

Where I think it would be better formatted as:

```
SELECT DISTINCT
    a,
    b,
    c
FROM
    d
```

**Comment by darold** [comment]
Sorry I have forgotten to apply other changes, commit 4207956 remove new line between SELECT and DISTINCT and add a new line after DISTINCT when the next keyword is not ON.
