### ISSUE TITLE
formatting replaces umlauts (ä, ö, ü, ß) with spaces

### ISSUE THREAD

**Issue by autinerd** [darold/pgFormatter#66]
When using pg_format on .sql files which contains names containing German umlauts, then these are replaced with spaces, even these are correct names in PostgreSQL.

**Comment by darold** [comment]
Please can you join a file with your query, not a copy/paste as the encoding will be changed. If you prefer you can sent it to my private email < gilles AT darold DOT net >

I can not reproduce the issue, if I use query:
```
SELECT * FROM my_table
WHERE col1 IN ('ä', 'ö', 'ü', 'ß');
```
the output is
```
SELECT
    *
FROM
    my_table
WHERE
    col1 IN ('ä', 'ö', 'ü', 'ß');
```
but encoding is  `UTF-8 Unicode text`.

**Comment by autinerd** [comment]
It's when the table name contains umlauts, like in https://github.com/firefly-serenity/datenbanken/blob/master/fähigkeiten.sql

**Comment by darold** [comment]
Such character are not allowed in object name, the name of your table need to be enclosed between double quote:
```
CREATE TABLE "fähigkeit" (
	faehnr INTEGER NOT NULL,
	faehbez VARCHAR(35) NOT NULL,
	PRIMARY KEY (faehnr)
);
```

**Comment by autinerd** [comment]
Okay, when I use the file in postgreSQL 11, it works without errors.

**Comment by darold** [comment]
Yes, that's works in PostgreSQL for a long time, but not in pgFormatter because I can not find a solution that works with all encoding. I can force the use of UTF8 but in this case a file in ISO8859 will produce invalid characters.

**Comment by autinerd** [comment]
Okay, no problem, thank you! Then I will use quotation marks when using umlauts.
