### ISSUE TITLE
Aggregate expressions (`ORDER BY`, `FILTER (WHERE ...)`) break column statements

### ISSUE THREAD

**Issue by leorochael** [darold/pgFormatter#68]
[Aggregate Expressions](https://www.postgresql.org/docs/11/static/sql-expressions.html#SYNTAX-AGGREGATES) allow specifying ordering and filtering on columns that are subject to aggregate functions.

They contain keywords like `WHERE` and `ORDER BY` which could trick pg_formatter into treating them as part of the top level query, causing line breaks in the middle, but not after, a column expression.

Also, `FILTER` is not recognized as a keyword (i.e. capitalized).

For example a statement like:

```
select
count(*) filter (where b) as count_b,
count(*) filter (where c) as count_c
from a
```

Is currently formatted as:

```sql
SELECT
    count(*) filter (
    WHERE
        b) AS count_b, count(*) filter (
    WHERE
        c) AS count_c
FROM
    a
```

Notice that the end of the `count_b` definition is in the same line as the start of the `count_c` definition but the line is broken just after the `WHERE`.

I'd expect it to render more like:

```
SELECT
    count(*) FILTER (WHERE b) AS count_b,
    count(*) FILTER (WHERE c) AS count_c
FROM
    a
```

Since the `WHERE` expression could be long, an alternative rendering could be:

```
SELECT
    count(*) FILTER (WHERE
        b
    ) AS count_b,
    count(*) FILTER (WHERE
        c
    ) AS count_c
FROM
    a
```

**Comment by darold** [comment]
Thanks for the report, last commits might solve this issue.

**Comment by leorochael** [comment]
Looks good to me.  You can close this issue if you want.
