### ISSUE TITLE
Array declaration and subscripting operator spaces

### ISSUE THREAD

**Issue by boromisp** [darold/pgFormatter#69]
I also have a similar issue with the sign of negative numbers.

Current implementation:
```sql
SELECT
    some_array [ 1 ],
    - 1,
    '{1}'::int [ ];
```

Expected result:
```sql
SELECT
    some_array[1],
    -1,
    '{1}'::int[];
```

Is this something that you would consider changing?
I'm fine with the current behavior if it is deliberate (my goal is consistency while maintaining readability), it just seems unusual to me.

**Comment by darold** [comment]
This was the default behavior of pgFormatter but I also think it is unusual. Commits e249a75 adds this formatting and commit f526762 also remove newline after a comma int ARRAY[] definition.

Thanks for the report.

**Comment by boromisp** [comment]
Thanks, works as expected.
