### ISSUE TITLE
Mangles some operators. Silly formating for Geo types

### ISSUE THREAD

**Issue by dbenhur** [darold/pgFormatter#7]
```sql
SELECT * FROM foo
WHERE ( ( status = 1 AND circle ( POINT ( 47.6115,  - 122.3343 ), 2.36 ) @> latLong )
 OR circle ( POINT ( 47.6115,- 122.3343 ), 0.1 ) @> latLong
```
becomes 
```sql
SELECT
    *
FROM
    foo
WHERE (
    (
        STATUS = 1
        AND circle (
            point (
                47.6115,
                - 122.3343 ),
            2.36 )
        @ > latLong )
    OR circle (
        point (
            47.6115,
            - 122.3343 ),
        0.1 )
    @ > latLong
```
Erroneously adding a space between `@` & `>` of the [contains operator](http://www.postgresql.org/docs/9.4/static/functions-geometry.html); I suspect similar behavior for a bunch of other geo and array operators supplied by Postgresql. Breaking the `CIRCLE( POINT(x,y), r)` over several lines just makes it really hard to read.

**Comment by darold** [comment]
Thanks for the report, geometric operators have been added into last commit 2e0417e.
