### ISSUE TITLE
COMMIT statement has extra new line on format.

### ISSUE THREAD

**Issue by lifeiscontent** [darold/pgFormatter#70]
when writing a BEGIN and COMMIT statement in sql the commit statement gets formatted to have 2 new lines instead of 1.

**Comment by darold** [comment]
Please post an example.

**Comment by lifeiscontent** [comment]
@darold sorry for not getting to this sooner.

```diff
 -- Deploy schemas/custom/grants/grant_schema_to_authenticated to pg
-
 -- requires: schemas/custom/schema
-
 BEGIN;

-GRANT USAGE ON SCHEMA custom
-TO authenticated;
+GRANT USAGE ON SCHEMA custom TO authenticated;

 COMMIT;
+
```

my expectations here would be:

1. new line after last comment
2. no extra new line after `COMMIT;`

**Comment by darold** [comment]
Hi,

Commit bdbcefe adds a new line after a comment when it is not in a block or a statement.

About removing the new line after the `COMMIT;` I don't think it should be done. This line is a statement like any others and each statement that is not in a code block is separated with a new line for the next statement.

Regards,

**Comment by lifeiscontent** [comment]
@darold what about a case for if it's at the end of a file?

**Comment by darold** [comment]
I think having a single new line character at end of file is not really a problem or at least there is more urging fixes that need works. I'm closing the issue but if there is more demand on solving this extra new line I will reopen it. Thanks.
