### ISSUE TITLE
comments should get trimmed

### ISSUE THREAD

**Issue by lifeiscontent** [darold/pgFormatter#71]
when creating a comment like so

the white space should be removed

``` diff
- -- this is my comment 
+ -- this is my comment
```

**Comment by darold** [comment]
Last commit 3f151ea might fix this issue as well as some others related to comments.

**Comment by lifeiscontent** [comment]
@darold you’re my GitHub super hero! Great work. 🎉

**Comment by darold** [comment]
Thanks :-)

**Comment by lifeiscontent** [comment]
@darold is there a new release for this?

**Comment by darold** [comment]
Maybe this weekend if I find enough time.

**Comment by darold** [comment]
Just published v3.3
