### ISSUE TITLE
more readable medium-large arity functions

### ISSUE THREAD

**Issue by pyramation** [darold/pgFormatter#74]
Here are some example changes. The red is the original code that I wrote, and as you can see, the formatter put them all on one line, which for large arity functions is hard to read.

<img width="560" alt="screen shot 2018-11-30 at 10 50 49 am" src="https://user-images.githubusercontent.com/545047/49293250-4251f180-f48e-11e8-8763-d887eee57ad0.png">

Is there a way to put arguments for functions on multiple lines for readability?

**Comment by pyramation** [comment]
example input and output if it's useful:

input

```sql
CREATE FUNCTION large_arity_function
    arg1 text,
    arg2 text,
    arg3 text,
    arg4 text,
    arg5 text,
    arg6 text,
    arg7 text
) RETURNS void AS $$
BEGIN
    PERFORM 1;
END;
$$
LANGUAGE 'plpgsql'
VOLATILE
SECURITY DEFINER;
```

output

```sql
CREATE FUNCTION large_arity_function arg1 text, arg2 text, arg3 text, arg4 text, arg5 text, arg6 text, arg7 text)
    RETURNS void
    AS $$
BEGIN
    PERFORM
        1;
END;
$$
LANGUAGE 'plpgsql'
VOLATILE
SECURITY DEFINER;

```

**Comment by darold** [comment]
This is the right formatting. If you generate a pg_dump of a function you will have such output, all parameters are on a single line. pgFormatter tries to be the closest of pg_dump output. I understand that with lot of parameters this can be too strict, I will add a parameter to be able to change this behavior.

**Comment by pyramation** [comment]
that would be great to have an option for this!

**Comment by darold** [comment]
Commit 1e2fc1e adds this feature when using `-t` option.

**Comment by pyramation** [comment]
remarkable! Thanks again @darold for making all the changes, this is greatly going to improve our workflow!
