### ISSUE TITLE
more readable policies

### ISSUE THREAD

**Issue by pyramation** [darold/pgFormatter#75]
I was wondering if there is a way to make policies more readable. Here is some code as input

```sql
CREATE POLICY can_select_object ON object
  FOR SELECT
  USING (
    can_do_the_thing(get_current_user(), owner_id)
  );

CREATE POLICY can_insert_object ON object
  FOR INSERT
  WITH CHECK (
    can_do_the_thing(get_current_user(), owner_id)
  );

CREATE POLICY can_update_object ON object
  FOR UPDATE
  USING (
    can_do_the_thing(get_current_user(), owner_id)
  );

CREATE POLICY can_delete_object ON object
  FOR DELETE
  USING (
    can_do_the_thing(get_current_user(), owner_id)
  );
```

And here is the output:

```sql
CREATE POLICY can_select_object ON object FOR
    SELECT
        USING (
            can_do_the_thing (get_current_user (),
                owner_id)
);

CREATE POLICY can_insert_object ON object FOR INSERT WITH CHECK (
    can_do_the_thing (
        get_current_user (
), owner_id
)
);

CREATE POLICY can_update_object ON object
FOR UPDATE
USING (
    can_do_the_thing (get_current_user (),
        owner_id)
);

CREATE POLICY can_delete_object ON object FOR DELETE
USING (
    can_do_the_thing (get_current_user (),
        owner_id)
);
```

Is there a way to keep it consistent like the input? I feel that it's more readable.

**Comment by pyramation** [comment]
I totally understand the idea of respecting the PostgreSQL default formatting! I completely agree for the defaults it makes complete sense. I'm curious though, if through some options developers could opt-in to some specific options. I'm not sure if you're aware, but many developers are using your code to write SQL in real time, and have it formatted when they hit save:

* https://marketplace.visualstudio.com/items?itemName=bradymholt.pgformatter
* https://atom.io/packages/pg-formatter

So without this type of option a developer that is writing a POLICY that uses a plugin that depends on pgFormatter (a lot of devs are using prettier and syntax formatting within atom or vscode these days), unless their wordwrap is on, would end up having to edit policies on a single line.

Do you think this use case of your system  could justify an option to format policies similar to the docs above?

**Comment by darold** [comment]
Commit bfd9bcd add the `-t` option that will force multiline in POLICY and PUBLICATION statements. Here a sample of the output:
```
$ perl pg_format -t policy.sql 
CREATE POLICY can_select_object ON object
    FOR SELECT
        USING (can_do_the_thing (get_current_user (), owner_id));

CREATE POLICY can_insert_object ON object
    FOR INSERT
        WITH CHECK (can_do_the_thing (get_current_user (), owner_id));

CREATE POLICY can_update_object ON object
    FOR UPDATE
        USING (can_do_the_thing (get_current_user (), owner_id));

CREATE POLICY can_delete_object ON object
    FOR DELETE
        USING (can_do_the_thing (get_current_user (), owner_id));
```

**Comment by pyramation** [comment]
this is absolutely great. I just ran `pg_format` w `-t` on a large number of files, looks wonderful. Thanks @darold !!
