### ISSUE TITLE
In text mode, please don't print the line of ---- first by default

### ISSUE THREAD

**Issue by davidfetter** [darold/pgFormatter#8]
It's ugly.

**Comment by darold** [comment]
Hi David,

What are you talking about? Is it related to the annouce? You mean to not add ------ under title? If not please provide an example.

Best regards

**Comment by davidfetter** [comment]
On Thu, Mar 19, 2015 at 10:47:58AM -0700, Darold wrote:
> Hi David,
> 
> What are you talking about? Is it related to the annouce? You mean to not add ------ under title? If not please provide an example.
> 
> Best regards

Here's what I mean:

$ echo "select * from foo" | pg_format -
--------------------------------------------------------------------------------
SELECT
    *
FROM
    foo

The first line of the output is unneeded and unwanted.

Cheers,
David.
-- 
David Fetter <david@fetter.org> http://fetter.org/
Phone: +1 415 235 3778  AIM: dfetter666  Yahoo!: dfetter
Skype: davidfetter      XMPP: david.fetter@gmail.com

Remember to vote!
Consider donating to Postgres: http://www.postgresql.org/about/donate

**Comment by darold** [comment]
Damn, I test with too big queries to see this line, I've completly forgotten it :-)
Commit 1828f59 remove that unecessary line.

Cheers
