### ISSUE TITLE
Not all comments are removed

### ISSUE THREAD

**Issue by romani** [darold/pgFormatter#80]
http://sqlformat.darold.net/
```
/** comment1 */
-- comment2

select * from table;
```
select "Remove Comments" options 
press "Format my code"

result:
```
-- comment2

SELECT
    *
FROM
    TABLE;
```

Detected: not all comments are removed
Expected: all comments are removed

**Comment by darold** [comment]
Commit 035db07 solves this issue, thanks for the report.
