### ISSUE TITLE
WHERE clause in previous CTE preventing newlines for columns in next CTE

### ISSUE THREAD

**Issue by cfmeyers** [darold/pgFormatter#83]
Firstly, thank you for open-sourcing this, it's a great tool!

I'm using pg_format version 3.3 (this issue is also happening in the web demo).

It looks like putting a `WHERE` clause in the previous CTE is keeping `pg_format` from breaking columns out into newlines in the next CTE (the line with `style, body`): 

```sql
WITH styles AS (
    SELECT
        style,
        color
    FROM
        style_table s
    WHERE
        s.id = 'D'
),
reviews AS (
    SELECT
        style, body
    FROM
        review_table
)
SELECT
    *
FROM
    styles s
```
That second CTE should be:
```sql
...
reviews AS (
    SELECT
        style, 
        body
    FROM
        review_table
)
...
```
Removing the `WHERE` in the first CTE fixes the problem in the second CTE:
```sql
WITH styles AS (
    SELECT
        style,
        color
    FROM
        style_table s
),
reviews AS (
    SELECT
        style,
        body
    FROM
        review_table
)
SELECT
    *
FROM
    styles s
```

**Comment by darold** [comment]
Commit 9535640 might fix this issue. Online site updated. Thanks.

**Comment by cfmeyers** [comment]
@darold thank you, this fixed it!
