### ISSUE TITLE
Upload file

### ISSUE THREAD

**Issue by HuanRuan** [darold/pgFormatter#86]
Hi

Using the `Upload file` button on the web interface for file* `test.sql` gives me an error `FATAL: Only text / plain files are supported ! Found application / octet - stream`. Renaming it to `test.sql.txt` works.

*The file was created by `notepad` on Windows. I have attached the `test.sql.txt` file as `.sql` extension is not an allowed attachment.
[test.sql.txt](https://github.com/darold/pgFormatter/files/2976344/test.sql.txt)

I would've thought `.sql` is a common extension for SQL code. Can it be supported please?

Thanks
Huan

**Comment by darold** [comment]
Hi,

My Apache/2.4.29 server returns content-type: `application/sql` which is supported by pgFormatter. Can you give me the type and version of web server you are using?

Regards,

**Comment by HuanRuan** [comment]
Hi Darold

I can reproduce this on http://sqlformat.darold.net/ so I presume it has something to do with my client environment, which is Windows 10 Pro, Chrome Version 72.0.3626.121 (Official Build) (64-bit) and Firefox 65.0.2 (64-bit).

As of my server, CentOS Linux release 7.6.1810,  Apache/2.4.6 (CentOS).

Thanks
Huan

**Comment by darold** [comment]
I have allowed application/octet-stream content-type to be uploaded, this should fix the issue. Le us know.

**Comment by HuanRuan** [comment]
Many thanks Darold. This works now.
