### ISSUE TITLE
Add option to retain blank lines between statements

### ISSUE THREAD

**Issue by ShonFrazier** [darold/pgFormatter#88]
I use blank lines to group statements for the benefits of the humans on my team reading my scripts. I am attempting to workaround by using comments to enforce formatting, but the team still prefers blank lines as spacing.

**Comment by darold** [comment]
Do you have an example of the output you are expecting to help me understand what blank lines mean?

**Comment by ShonFrazier** [comment]
```SQL
/* Insert values for environment 1 */
INSERT INTO table
    VALUES (1, 2, '3');

/* Insert values for environment 2 */
INSERT INTO table
    VALUES (2, 17, 'hello');
```
becomes
```SQL
/* Insert values for environment 1 */
INSERT INTO table 
    VALUES (1, 2, '3');
/* Insert values for environment 2 */
INSERT INTO table
    VALUES (2, 17, 'hello');
```

The blank line is eliminated. I would prefer to keep it.

**Comment by darold** [comment]
Thanks, commit c64412b adds this feature. The newline will always be added event if there was not in the original text. Online site have been updated, you can test the feature.
