### ISSUE TITLE
Is cast() a function or keyword?

### ISSUE THREAD

**Issue by HuanRuan** [darold/pgFormatter#89]
Hi Darold

On http://sqlformat.darold.net/, I choose `Functions` to `Lower case`, then format `select cast(1 as text)`, 
- In the browser view, I get
```sql
SELECT
    CAST(1 AS text)
```
- But, in browser Inspection, I get lower case 'cast'. This means, when I copy the content to clipboard, I get `CAST` from Chrome, but `cast` from Firefox.

Should it be `CAST` or `cast`? or is 'cast' considered a Keyword or Function?

Thanks
Huan

**Comment by darold** [comment]
Thanks, commit 4fed2b3 solves this issue. Online site have been updated.
