### ISSUE TITLE
Reset all

### ISSUE THREAD

**Issue by rimbault** [darold/pgFormatter#9]
Hi,

I use this very useful tools in CGI mode on a local server.
When I hit the "Reset All" button, the page is redirected to http://sqlformat.darold.net/
I've changed the value of "my $service_url", but, perhaps, $service_url can be initialized automatically ?

**Comment by darold** [comment]
Hi,

Last commit 222ff70 might set the redirection URL automatically, you don't have to change $service_url at all now.

Thanks,

**Comment by rimbault** [comment]
Thanks for this very quick fix !
