### ISSUE TITLE
EXCLUDE striped 

### ISSUE THREAD

**Issue by tim-field** [darold/pgFormatter#91]
input
```sql
ALTER TABLE truck
    ADD EXCLUDE
    USING gist (id WITH =, system_period WITH &&);
```

output
```sql
ALTER TABLE truck
    ADD
    USING gist (id WITH =, system_period WITH &&);
```

I'm using this library as part of the Visual code extension https://github.com/bradymholt/vscode-pgFormatter I'm not sure how to tell what version its using under the hood

**Comment by tim-field** [comment]
Running the example you have here, also causes this exclude keyword to be stripped 
https://github.com/darold/pgFormatter/blob/master/samples/ex39.sql

**Comment by darold** [comment]
Commit 90c3d4a fixes this issue, sample file and online site have been updated. Thanks for the report.
