### ISSUE TITLE
Is it OK to rely on List::Util package?

### ISSUE THREAD

**Issue by NisSAM** [darold/pgFormatter#92]
Functions **any** and **first** from [List::Util](https://perldoc.perl.org/List/Util.html) are ideal replacement for many  **grep**s in the **pgFormatter** code.

The only concern is - **pgFormatter** will depend on **List::Util** that is already included in many Perl distributions.

**Comment by darold** [comment]
I don't see any objection to use List::Util it is available by default on all system I use.
