### ISSUE TITLE
Wrong formating if column name ends with $ sign

### ISSUE THREAD

**Issue by NisSAM** [darold/pgFormatter#95]
`select price$, price#, price$test, price#test from dual`

is formatted as

```
select
    price $,
    price #,
    price $ test,
    price # test
from
    dual
```

**Comment by darold** [comment]
Commit c621f08 fixes this issue. Note that # is not allowed in object name it must be enclosed with double quote.
```
select price$, "price#", price$test, "price#test" from dual;
```
is now formatted as
```
SELECT
    price$,
    "price#",
    price$test,
    "price#test"
FROM
    dual;
```

**Comment by NisSAM** [comment]
Thank you. 
Just for your information. I format Oracle`s SQL. In the Oracle SQL '#' is allowed in names without any quotes :-)

**Comment by darold** [comment]
This was what I deduced from your query, the dual pseudo table give me a clue :-)
