### ISSUE TITLE
BEGIN WORK problem.

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#98]
This set of queries oddly indents all but the first line when run though pg_format 3.3 with the default settings.  This:

    BEGIN WORK;
    SELECT 1;
    COMMIT;

becomes:

    BEGIN
        WORK;
        SELECT
            1;
        COMMIT;

**Comment by darold** [comment]
Commit 825deb2 might fix this indentation issue. New output format will be:
```
BEGIN WORK;
SELECT
    1;
COMMIT;
```

**Comment by bmomjian** [comment]
OK, great.  I will wait for the update.  Thanks.
