### ISSUE TITLE
Suppress newline after keyword

### ISSUE THREAD

**Issue by bmomjian** [darold/pgFormatter#99]
Is there a way to limit the number of newlines added by pg_formatter?  For example, this:

    SELECT relname, relkind FROM pg_class;

with pg_formatter 3.3 becomes:

    SELECT
        relname,
        relkind
    FROM
        pg_class;

I would like it to be this:

    SELECT relname,
        relkind
    FROM pg_class;

I have found a way to hack sed to do this, but it is less than ideal.

**Comment by darold** [comment]
There currently no way to do this formatting but there is the `-t` option that is use to provide alternate formatting like this. I will see it it can do the job.

**Comment by bmomjian** [comment]
OK, thanks.  I don't see -t as documented, and got an odd error when I tried it:

$ pg_format -t
Uncaught exception: Deadly warning: Unknown option: t
 at /usr/bin/pg_format line 27.
        main::__ANON__("Unknown option: t\x{a}") called at /usr/share/perl/5.24/Getopt/Long.pm line 1072
        Getopt::Long::FindOption(ARRAY(0x55e4ba974730), "(--|-|\\+)", "--", "-t", HASH(0x55e4baf2fcb0)) called at /usr/share/perl/5.24/Getopt/Long.pm line 528
        Getopt::Long::GetOptionsFromArray(undef, undef, undef, undef, undef, undef, undef, undef, ...) called at /usr/share/perl5/pgFormatter/CLI.pm line 252
        pgFormatter::CLI::get_command_line_args(pgFormatter::CLI=HASH(0x55e4ba9742b0)) called at /usr/share/perl5/pgFormatter/CLI.pm line 62
        pgFormatter::CLI::run(pgFormatter::CLI=HASH(0x55e4ba9742b0)) called at /usr/bin/pg_format line 49
 at /usr/bin/pg_format line 19.
        main::__ANON__("Deadly warning: Unknown option: t\x{a} at /usr/bin/pg_format line"...) called at /usr/share/perl/5.24/Carp.pm line 168
        Carp::confess("Deadly warning: Unknown option: t\x{a}") called at /usr/bin/pg_format line 27
        main::__ANON__("Unknown option: t\x{a}") called at /usr/share/perl/5.24/Getopt/Long.pm line 1072
        Getopt::Long::FindOption(ARRAY(0x55e4ba974730), "(--|-|\\+)", "--", "-t", HASH(0x55e4baf2fcb0)) called at /usr/share/perl/5.24/Getopt/Long.pm line 528
        Getopt::Long::GetOptionsFromArray(undef, undef, undef, undef, undef, undef, undef, undef, ...) called at /usr/share/perl5/pgFormatter/CLI.pm line 252
        pgFormatter::CLI::get_command_line_args(pgFormatter::CLI=HASH(0x55e4ba9742b0)) called at /usr/share/perl5/pgFormatter/CLI.pm line 62
        pgFormatter::CLI::run(pgFormatter::CLI=HASH(0x55e4ba9742b0)) called at /usr/bin/pg_format line 49

**Comment by darold** [comment]
I don't have this error, what is the output of `pg_format --version`?

**Comment by darold** [comment]
Sorry, this option is only available in current development code, I have to publish a new release for some weeks now but I lack of time. Will do asap.

**Comment by bmomjian** [comment]
$ pg_format --version
pg_format version 3.3

**Comment by bmomjian** [comment]
Also, has there been any thought of rolling up multiple comma-separated options into single lines, with some kind of maximum length, so the output query would become:

    SELECT relname, relkind
    FROM pg_class;

**Comment by darold** [comment]
Something like `--wrap_after NCOLS` :-) I will look how it can be done.

**Comment by bmomjian** [comment]
Yes, that would be very nice.  :-)

**Comment by bmomjian** [comment]
FYI, I am using the PGDG Debian package.

**Comment by darold** [comment]
Ok, usually it is updated a few days after a new release. Forgot to say that the online demo site at http://sqlformat.darold.net/ is always up-to-date with latest development code so if you want to test the last fix it is already available. There is also the `Alternate formatting` checkbox the equivalent to `-t` CLI option.

**Comment by bmomjian** [comment]
OK, thanks.

**Comment by darold** [comment]
Hi Bruce,

Commit a62d134 adds this feature:
```
Add -W, --wrap-after option to set number of column after which lists
must be wrapped. Default: puts every item on its own line. This applies
to SELECT and FROM list. For example the following query:

    SELECT a, b, c, d FROM t_1, t_2, t3 WHERE a = 10 AND b = 10;

is formatted into:

    SELECT a, b, c, d
    FROM t_1, t_2, t3
    WHERE a = 10
        AND b = 10;

Note this formatting doesn't fits well with sub queries in list.
```
You can test the feature on the demo site http://sqlformat.darold.net/ with the new option "Wrap after" in the "Indentation" section. Let me know your feedback.

Cheers

**Comment by bmomjian** [comment]
On Sat, Apr 20, 2019 at 01:46:12PM -0700, Gilles Darold wrote:
> Hi Bruce,
> 
> Commit a62d134 adds this feature:
> 
> Add -W, --wrap-after option to set number of column after which lists
> must be wrapped. Default: puts every item on its own line. This applies
> to SELECT and FROM list. For example the following query:
> 
>     SELECT a, b, c, d FROM t_1, t_2, t3 WHERE a = 10 AND b = 10;
> 
> is formatted into:
> 
>     SELECT a, b, c, d
>     FROM t_1, t_2, t3
>     WHERE a = 10
>         AND b = 10;
> 
> Note this formatting doesn't fits well with sub queries in list.
> 
> You can test the feature on the demo site http://sqlformat.darold.net/ with the
> new option "Wrap after" in the "Indentation" section. Let me know your
> feedback.

Oh, very nice, thanks.

-- 
  Bruce Momjian  <bruce@momjian.us>        http://momjian.us
  EnterpriseDB                             http://enterprisedb.com

+ As you are, so once was I.  As I am, so you will be. +
+                      Ancient Roman grave inscription +
